<!DOCTYPE html>
<html lang="zh" dir="auto">

<head><script src="/livereload.js?mindelay=10&amp;v=2&amp;port=1313&amp;path=livereload" data-no-instant defer></script><meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="robots" content="index, follow">
<title>啪，还敢抛出异常 | PaperMod</title>
<meta name="keywords" content="Java, 后端">
<meta name="description" content="Java异常处理是Java编程中非常重要的一部分。本文简要介绍了异常的概念和Java中的异常处理机制。通过学习本文，您将了解如何使用try-catch语句捕获和处理异常，以及如何使用throws关键字">
<meta name="author" content="程序员晓凡">
<link rel="canonical" href="http://localhost:1313/posts/juejin/%E5%95%AA%E8%BF%98%E6%95%A2%E6%8A%9B%E5%87%BA%E5%BC%82%E5%B8%B8/">
<meta name="google-site-verification" content="XYZabc">
<link crossorigin="anonymous" href="/assets/css/stylesheet.7b92bf4867c997b58ec50f63451b83777173d5bd5593376852abd85746d09d71.css" integrity="sha256-e5K/SGfJl7WOxQ9jRRuDd3Fz1b1VkzdoUqvYV0bQnXE=" rel="preload stylesheet" as="style">
<link rel="icon" href="http://localhost:1313/%3Clink%20/%20abs%20url%3E">
<link rel="icon" type="image/png" sizes="16x16" href="http://localhost:1313/%3Clink%20/%20abs%20url%3E">
<link rel="icon" type="image/png" sizes="32x32" href="http://localhost:1313/%3Clink%20/%20abs%20url%3E">
<link rel="apple-touch-icon" href="http://localhost:1313/%3Clink%20/%20abs%20url%3E">
<link rel="mask-icon" href="http://localhost:1313/%3Clink%20/%20abs%20url%3E">
<meta name="theme-color" content="#2e2e33">
<meta name="msapplication-TileColor" content="#2e2e33">
<link rel="alternate" hreflang="zh" href="http://localhost:1313/posts/juejin/%E5%95%AA%E8%BF%98%E6%95%A2%E6%8A%9B%E5%87%BA%E5%BC%82%E5%B8%B8/">
<noscript>
    <style>
        #theme-toggle,
        .top-link {
            display: none;
        }

    </style>
</noscript><meta property="og:title" content="啪，还敢抛出异常" />
<meta property="og:description" content="Java异常处理是Java编程中非常重要的一部分。本文简要介绍了异常的概念和Java中的异常处理机制。通过学习本文，您将了解如何使用try-catch语句捕获和处理异常，以及如何使用throws关键字" />
<meta property="og:type" content="article" />
<meta property="og:url" content="http://localhost:1313/posts/juejin/%E5%95%AA%E8%BF%98%E6%95%A2%E6%8A%9B%E5%87%BA%E5%BC%82%E5%B8%B8/" />
<meta property="og:image" content="http://localhost:1313/images/papermod-cover.png" />
<meta property="article:section" content="posts" />
<meta property="article:published_time" content="2023-07-09T00:00:00+00:00" />
<meta property="article:modified_time" content="2023-07-09T00:00:00+00:00" />


<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:image" content="http://localhost:1313/images/papermod-cover.png" />
<meta name="twitter:title" content="啪，还敢抛出异常"/>
<meta name="twitter:description" content="Java异常处理是Java编程中非常重要的一部分。本文简要介绍了异常的概念和Java中的异常处理机制。通过学习本文，您将了解如何使用try-catch语句捕获和处理异常，以及如何使用throws关键字"/>


<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [
    {
      "@type": "ListItem",
      "position":  1 ,
      "name": "Posts",
      "item": "http://localhost:1313/posts/"
    }, 
    {
      "@type": "ListItem",
      "position":  2 ,
      "name": "啪，还敢抛出异常",
      "item": "http://localhost:1313/posts/juejin/%E5%95%AA%E8%BF%98%E6%95%A2%E6%8A%9B%E5%87%BA%E5%BC%82%E5%B8%B8/"
    }
  ]
}
</script>
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "BlogPosting",
  "headline": "啪，还敢抛出异常",
  "name": "啪，还敢抛出异常",
  "description": "Java异常处理是Java编程中非常重要的一部分。本文简要介绍了异常的概念和Java中的异常处理机制。通过学习本文，您将了解如何使用try-catch语句捕获和处理异常，以及如何使用throws关键字",
  "keywords": [
    "Java", "后端"
  ],
  "articleBody": "前言 去年又重新刷了路遥的《平凡的世界》，最近也在朋友推荐下，来看了路遥的另一部成名作《人生》。 故事中的主人公高加林，虽生在农村，面朝黄土背朝天，却不甘心像父辈一样或者，一心想着摆脱民语的束缚，追求他的理想生活。 然而命运多舛，在他所想象的理想生活中，一次次跌倒，最终不得不承认自己的平凡，生活总得继续。 现实世界如此，代码世界里，我们也希望一切都是理想的。 我们希望用户输入的数据格式永远是正确的，打开的资源也一定存在，用户的硬件是正常的，用户的操作系统四稳定的，用户的网络也一定是畅通的等等 然而事与愿违，愿望是好的，现实是残酷的。 引入异常机制的目的就在于，当“人生”中出现异常时，能够将其捕获并处理，保证我们能更好的走下去，不至于出现一点插曲，就停滞不前。\n一、异常引入 因此呢就出现了异常处理，我们把可能出现异常的业务代码放到try块中定义，把异常处理放到catch块中进行处理，保证程序遇到异常依然能继续运行，保证程序的健壮性。\n① 我们来看看高加林的一生中各种异常的处理\njava\n代码解读\n复制代码\ntry{ //业务逻辑，高加林的一生 System.out.println(\"1、高中毕业，虽然没考上大学。却不断学习，在报纸上发表诗歌和散文，参加考试，谋得一份临时教师职位\"); System.out.println(\"2、高加林的叔叔从外地回到家乡工作，在县城担任劳动局局长,副局长为了讨好新上任的局长;\"); System.out.println(\"便私下给高加林走了后门，就这样高加林成为了公职人员\"); System.out.println(\"3、与高中同学黄亚萍相遇，再次相遇的两个人，志趣相投，相聊甚欢。高加林以为攀上黄亚萍这个高枝，能到大城市一展宏图\"); }catch(ExceptionClass1 e1){ System.out.println(\"第一个异常发生，教师职位被他人顶替\"); System.out.println(\"没有了工作，重新回到农村，成为最不想当的农民\"); System.out.println(\"很快加入村里的劳动队伍里，白天努力劳作，晚上看书学习，等待着东山再起的机会\"); }catch(ExceptionClass2 e2){ System.out.println(\"第二个异常发生，遭人举报走后门\"); System.out.println(\"再次丢了工作，一直想摆脱农名身份的他，再次成为了农民\"); }catch(ExceptionClass3 e3){ System.out.println(\"第三个异常发生，纸包不住火，黄亚萍及其家人知道了高加林遭遇举报\"); System.out.println(\"被打回原型，和黄亚萍断绝了关系\"); System.out.println(\"黄亚萍不想高加林回农村，希望高加林去找叔父帮忙，看是否可以继续留下来\"); }catch(Exception e){ System.out.println(\"再次跌倒的他，没再去找叔父\"); System.out.println(\"有了清醒的认知，自己的路还是得靠自己走下去\"); }finally{ System.out.println(\"接受现实，更好的走下去\"); }\n② 代码中\njava\n代码解读\n复制代码\n//未处理异常，程序遇到异常没法继续执行 public class ExceptionTest { public static void main(String[] args) { int num1 =7; int num2 =0; int res = num1/num2; System.out.println(\"程序继续执行......\"); } } //输出 Exception in thread \"main\" java.lang.ArithmeticException: / by zero at ExceptionTest.main(ExceptionTest.java:5)\n加入异常处理\njava\n代码解读\n复制代码\n//加入异常处理，程序遇到异常后继续运行 public class ExceptionTest { public static void main(String[] args) { int num1 =7; int num2 =0; try { int res = num1/num2; } catch (Exception e) { System.out.println(e.getMessage()); } System.out.println(\"程序继续执行......\"); } } //输出 / by zero 程序继续执行......\n小结： 如果执行try块里的业务逻辑代码出现异常，系统会自动生成一个异常对象，该异常对象被体骄傲给Java运行时环境，这个过程成为抛出异常 Java运行时环境收到异常对象时，会寻找能处理异常对象的catch块，如果找到合适的catch块，则把该异常对象交给该catch块处理，这个过程被成为异常捕获； 如果Java运行环境找不到捕获异常的catch块，则运行时环境终止，Java程序已将退出\n二、基本概念 程序执行中发生的不正常情况（语法错误逻辑错误不是异常）称为异常，所有的异常都继承与java.lang.Throwable 。Throwable 有两个重要子类\nError(错误)：Java虚拟机无法解决的严重问题，我们没办法通过 catch 来进行捕获 。如：内存溢出（OutOfMemoryError）、Java 虚拟机运行错误（Virtual MachineError）、类定义错误（NoClassDefFoundError）等。error 是严重错误，Java虚拟机会选择线程终止 Exception(异常)：编程错误或偶尔的外在因素导致的一般问题，程序本身可以处理的异常，可以通过 catch 来进行捕获。Exception 又可以分 运行时异常（程序运行时发生的异常）和编译时异常（程序编译期间产生的异常，必须要处理的异常，否则代码没法编译通过）。 三、异常继承体系 注：虚线为实现，实线为继承 四、常见运行异常 4.1 NullPointerException 空指针异常 java\n代码解读\n复制代码\npublic class ExceptionTest { public static void main(String[] args) { String str = null; System.out.println(str.length()); } } //输出 Exception in thread \"main\" java.lang.NullPointerException at ExceptionTest.main(ExceptionTest.java:4)\n4.2 ArithmeticException 数学运算异常 java\n代码解读\n复制代码\npublic class ExceptionTest { public static void main(String[] args) { int num1=7; int num2=0; int res = num1/num2; } } //输出 Exception in thread \"main\" java.lang.ArithmeticException: / by zero at ExceptionTest.main(ExceptionTest.java:5)\n4.3 ArrayIndexOutOfBoundsException 数组下标越界异常 java\n代码解读\n复制代码\npublic class ExceptionTest { public static void main(String[] args) { String strarr[] ={\"个人博客\",\"www.xiezhrspace.cn\",\"公众号\",\"XiezhrSpace\"}; //注意数组下标时从0开始的 for (int i = 0; i \u003c= strarr.length; i++) { System.out.println(strarr[i]); } } } //输出 个人博客 www.xiezhrspace.cn 公众号 XiezhrSpace Exception in thread \"main\" java.lang.ArrayIndexOutOfBoundsException: 4 at ExceptionTest.main(ExceptionTest.java:5)\n4.4 ClassCastException 类型转换异常 java\n代码解读\n复制代码\npublic class ExceptionTest { public static void main(String[] args) { Class1 class1 = new Class2(); //向上转型 Class2 class2 = (Class2)class1; //向下转型 Class3 class3= (Class3)class1; //两个类没有关系，转型失败 } } class Class1{} class Class2 extends Class1{}; class Class3 extends Class1{}; //输出 Exception in thread \"main\" java.lang.ClassCastException: Class2 cannot be cast to Class3 at ExceptionTest.main(ExceptionTest.java:5)\n4.5 NumberFormatException 数字格式不正确异常 java\n代码解读\n复制代码\npublic class ExceptionTest { public static void main(String[] args) { String str1 =\"123\"; String str2 = \"abc\"; System.out.println(Integer.valueOf(str1)); //可以转成功 System.out.println(Integer.valueOf(str2)); } } //输出 123 Exception in thread \"main\" java.lang.NumberFormatException: For input string: \"abc\" at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) at java.lang.Integer.parseInt(Integer.java:580) at java.lang.Integer.valueOf(Integer.java:766) at ExceptionTest.main(ExceptionTest.java:6)\n五、常见编译时异常 编译期间就必须处理的异常，否则代码不能通过编译 5.1 FileNotFoundException 操作一个不存在的文件时候发生异常 5.2 ClassNotFoundException 加载类，类不存在时异常 5.3 SQLException 操作数据库，查询表时发生异常 5.4 IllegalArgumentException 参数不匹配时发生异常 六、异常处理 Java 的异常处理通过 5 个关键字来实现：try、catch、throw、throws 和finally。 try catch 语句用于捕获并自行处理异常 finally 语句用于在任何情况下（除特殊情况外）都必须执行的代码 throw 手动生成异常对象 throws 将发生的异常抛出，交给调用者处理，最顶级的处理者是JVM\n6.1 异常处理方式 try-catch-finally :在代码中捕获异常自行处理 throws ：将发生的异常抛出，交给调用者处理，最顶级处理者是JVM 注： try-catch-finally 和throws 任选一种即可\n6.2 异常处理 6.2.1 try-catch-finally ①原理图 ②语法结构\njava\n代码解读\n复制代码\ntry { 逻辑程序块 //可能有异常的代码 } catch(Exception e) { /* ①发生异常时，系统将异常封装成Exception对象e，并传递给catch ②得到异常Exception e 后，程序员自行处理 注：只有发生异常时候，catch代码块才执行 */ 捕获异常 throw(e); } finally { 释放资源代码块 }\n③实例 小提示：选中代码，按下快捷键ctrl+alt+t 可以呼出代码提示\njava\n代码解读\n复制代码\npublic class TestException { public static void main(String[] args) { int num1 =10; int num2 =0; try { int num3=num1/num2; }catch (Exception e){ e.printStackTrace(); }finally { System.out.println(\"finally代码块被执行了\"); } System.out.println(\"程序继续执行...\"); } } //输出 java.lang.ArithmeticException: / by zero at com.xiezhr.TestException.main(TestException.java:9) finally代码块被执行了 程序继续执行...\n上述代码中，把可能出现异常的代码num1/num2; 放到了try语句块中，当代码发生异常时，在catch中捕获异常，并打印异常。不管有没有发生异常，finally 语句块里的代码都会执行。发生异常后程序并没有终止，最后输出 “程序继续执行…”\n6.2.2 try-with-resources Java中，对于文件操作IO流、数据库连接等开销非常昂贵的资源，用完之后必须及时通过close方法将\u003e其关闭，否则资源会一直处于打开状态，可能会导致内存泄露等问题。 关闭资源的常用方式就是在finally块里调用close方法将资源关闭\n所以对于流的操作我们经常回用到如下代码\njava\n代码解读\n复制代码\n//读取文本文件的内容 import java.io.File; import java.io.FileNotFoundException; import java.util.Scanner; public class TestException { public static void main(String[] args) { Scanner scanner = null; try { scanner = new Scanner(new File(\"D://xiezhr.txt\")); while (scanner.hasNext()) { System.out.println(scanner.nextLine()); } } catch (FileNotFoundException e) { e.printStackTrace(); } finally { if (scanner != null) { scanner.close(); } } } } //输出 个人博客：www.xiezhrspace.cn 个人公众号：XiezhrSpace 欢迎你关注\n分析： 上述代码中我们通过io流读取D盘xiezhr.txt文件中的内容，并将其内容按行打印出来。最后在finally代码块中将scanner关闭\nJava 7 之后，新的语法糖 try-with-resources 可以简写上述代码\njava\n代码解读\n复制代码\nimport java.io.File; import java.io.FileNotFoundException; import java.util.Scanner; public class TestException { public static void main(String[] args) { try(Scanner scanner = new Scanner(new File(\"D://xiezhr.txt\"))){ while (scanner.hasNext()) { System.out.println(scanner.nextLine()); } }catch (FileNotFoundException e){ e.printStackTrace(); } } } //输出 个人博客：www.xiezhrspace.cn 个人公众号：XiezhrSpace 欢迎你关注\n两段代码实现的功能是一样的，但明显try-with-resources 写法简单了好多。我们也更提倡优先使用 try-with-resources 而不是try-finally。\n6.2.3 抛出异常 当一个方法产生某种异常，但是不确定如何处理这种异常，那么就需要在该方法的头部显示地申明抛出异常，表明该方法将不对这些异常进行处理，而用该方法调用者负责处理\n6.2.3.1 thorows ①语法格式 returnType method_name(paramList) throws Exception 1,Exception2,…{…}\nreturnType 表示返回值类型 method_name 表示方法名 paramList 表示参数列表； Exception 1，Exception2，… 表示异常类 如果有多个异常类，它们之间用逗号分隔。这些异常类可以是方法中调用了可能拋出异常的方法而产生的异常，也可以是方法体中生成并拋出的异常 ②使用场景 当前方法不知道如何处理这种类型的异常，该异常应该由向上一级的调用者处理； 如果 main 方法也不知道如何处理这种类型的异常，也可以使用 throws 声明抛出异常，该异常将交给 JVM 处理。 JVM 对异常的处理方法是，打印异常的跟踪栈信息，并中止程序运行，这就是前面程序在遇到异常后自动结束的原因\n③实践操作\njava\n代码解读\n复制代码\nimport java.io.File; import java.io.IOException; import java.util.Scanner; public class TestException { //定义方法时声明抛出异常，方法中出现的异常自己不处理，交由调用者处理 public void readfile() throws IOException { // 读取文件 Scanner scanner = new Scanner(new File(\"D://xiezhr.txt\")); while (scanner.hasNext()) { System.out.println(scanner.nextLine()); } scanner.close(); } public static void main(String[] args) { TestException tt = new TestException(); try { //调用readfile方法 tt.readfile(); } catch (IOException e) { //打印异常 e.printStackTrace(); } } } //输出 个人博客：www.xiezhrspace.cn 个人公众号：XiezhrSpace 欢迎你关注\n分析： 以上代码，首先在定义 readFile() 方法时用 throws 关键字声明在该方法中可能产生的异常，然后在 main() 方法中调用readFile() 方法，并使用 catch 语句捕获产生的异常\n④ 异常处理流程图 注意：子类方法声明抛出的异常类型应该是父类方法声明抛出的异常类型的子类或相同，子类方法声明抛出的异常不允许比父类方法声明抛出的异常多。\n//下面程序编译就报错，原因时子类抛出比父类还大的异常\njava\n代码解读\n复制代码\npublic class OverrideThrows { public void test() throws IOException { FileInputStream fis = new FileInputStream(\"a.txt\"); } } class Sub extends OverrideThrows { // 子类方法声明抛出了比父类方法更大的异常 public void test() throws Exception { } }\n6.2.3.1 throw throw用来直接抛出一个异常\n①语法 throw ExceptionObject;\nExceptionObject 必须是 Throwable 类或其子类的对象 如果是自定义异常类，也必须是 Throwable 的直接或间接子类 ②执行原理 throw 语句执行时，它后面的语句将不执行； 此时程序转向调用者程序，寻找与之相匹配的 catch 语句，执行相应的异常处理程序。 如果没有找到相匹配的 catch 语句，则再转向上一层的调用程序。这样逐层向上，直到最外层的异常处理程序终止程序并打印出调用栈情况\n③实践操作\njava\n代码解读\n复制代码\nimport java.util.Scanner; public class TestException { public boolean validateUserName(String username) { boolean con = false; if (username.length() \u003e4) { // 判断用户名长度是否大于8位 if (\"admin\".equals(username)) { con = true; }else{ throw new IllegalArgumentException(\"你输入的用户名不对\"); } } else { throw new IllegalArgumentException(\"用户名长度必须大于 4 位！\"); } return con; } public static void main(String[] args) { TestException te = new TestException(); Scanner input = new Scanner(System.in); System.out.println(\"请输入用户名：\"); String username = input.next(); try { boolean con = te.validateUserName(username); if (con) { System.out.println(\"用户名输入正确！\"); } } catch (IllegalArgumentException e) { System.out.println(e); } } } //输出 ① 请输入用户名： abc java.lang.IllegalArgumentException: 用户名长度必须大于 4 位！ ② 请输入用户名： abcdef java.lang.IllegalArgumentException: 你输入的用户名不对 ③ 请输入用户名： admin 用户名输入正确！\n6.2.4 自定义异常 当Java提供的内置异常类型不能满足我们的需求时，我们可以设计自己的异常类型。\n①语法格式 class XXXException extends Exception|RuntimeException\n一般将自定义异常类的类名命名为 XXXException，其中 XXX 用来代表该异常的作用 自定义异常类需要继承 Exception 类或其子类，如果自定义运行时异常类需继承 RuntimeException 类或其子类 自定义异常类一般包含两个构造方法：一个是无参的默认构造方法，另一个构造方法以字符串的形式接收一个定制的异常消息，并将该消息传递给超类的构造方法。 ②实践操作\njava\n代码解读\n复制代码\nimport java.util.Scanner; public class TestException { public static void main(String[] args) { int age; Scanner scanner = new Scanner(System.in); System.out.println(\"请输入你的年龄\"); age=scanner.nextInt(); try { if(age \u003c 0) { throw new AgeException(\"您输入的年龄为负数！输入有误！\"); } else if(age \u003e 100) { throw new AgeException(\"您输入的年龄大于100！输入有误！\"); } else { System.out.println(\"您的年龄为：\"+age); } } catch (AgeException e) { e.printStackTrace(); } } } //输出 ① 请输入你的年龄 120 com.xiezhr.AgeException: 您输入的年龄大于100！输入有误！ at com.xiezhr.TestException.main(TestException.java:15) ② 请输入你的年龄 -34 com.xiezhr.AgeException: 您输入的年龄为负数！输入有误！ at com.xiezhr.TestException.main(TestException.java:13) ③ 请输入你的年龄 30 您的年龄为：30\n6.2.5 多异常捕获 Java7以后，catch 语句可以有多个，用来匹配多个异常\n①语法格式\njava\n代码解读\n复制代码\ntry{ // 可能会发生异常的语句 } catch (IOException | ParseException e) { // 异常处理 }\n多种异常类型之间用竖线|隔开 异常变量有隐式的 final 修饰，因此程序不能对异常变量重新赋值 ② 异常书写方式变化\njava\n代码解读\n复制代码\ntry{ // 可能会发生异常的语句 } catch (FileNotFoundException e) { // 调用方法methodA处理 } catch (IOException e) { // 调用方法methodA处理 } catch (ParseException e) { // 调用方法methodA处理 }\n变成\njava\n代码解读\n复制代码\ntry{ // 可能会发生异常的语句 } catch (FileNotFoundException | IOException | ParseException e) { // 调用方法处理 }\n③实践操作\njava\n代码解读\n复制代码\nimport java.util.Scanner; public class TestException { public static void main(String[] args) { int num1; int num2; try { Scanner scanner = new Scanner(System.in); System.out.println(\"请输入num1的值\"); num1=scanner.nextInt(); System.out.println(\"请输入num2的值\"); num2=scanner.nextInt(); int num= num1/num2; System.out.println(\"你输入的两个数相除，结果是\" + num); } catch (IndexOutOfBoundsException | NumberFormatException | ArithmeticException e){ System.out.println(\"程序发生了数组越界、数字格式异常、算术异常之一\"); e.printStackTrace(); } catch (Exception e) { System.out.println(\"未知异常\"); e.printStackTrace(); } } } //输出 ① 请输入num1的值 12 请输入num2的值 0 程序发生了数组越界、数字格式异常、算术异常之一 java.lang.ArithmeticException: / by zero at com.xiezhr.TestException.main(TestException.java:15) ② 请输入num1的值 6888888888 未知异常 java.util.InputMismatchException: For input string: \"6888888888\" at java.util.Scanner.nextInt(Scanner.java:2123) at java.util.Scanner.nextInt(Scanner.java:2076) at com.xiezhr.TestException.main(TestException.java:12) ③ 请输入num1的值 12 请输入num2的值 4 你输入的两个数相除，结果是3\n分析： 上面程序中IndexOutOfBoundsException|NumberFormatException|ArithmeticException来定义异常类型，这就表明该 catch 块可以同时捕获这 3 种类型的异常\n七、Throwable 类常用方法 String getMessage(): 返回异常发生时的简要描述 String toString(): 返回异常发生时的详细信息 String getLocalizedMessage(): 返回异常对象的本地化信息。使用 Throwable 的子类覆盖这个方法，可以生成本地化信息。如果子类没有覆盖该方法，则该方法返回的信息与 getMessage()返回的结果相同 void printStackTrace(): 在控制台上打印 Throwable 对象封装的异常信息 八、易混概念 8.1 Error和Exception的异同 Error 和Exception 都有共同的祖先Throwable，即Error 和Exception 都是Throwable的子类 Exception :程序本身可以处理的异常，可以通过 try-catch 来进行捕获。Exception又可以分为 Checked Exception (受检查异常，必须处理) 和 Unchecked Exception(不受检查异常，可以不处理)。 Error ：Error 属于程序无法处理的错误 ，我们没办法通过 try-catch 来进行捕获 。例如 Java 虚拟机运行错误（Virtual MachineError）、虚拟机内存不够错误(OutOfMemoryError)、类定义错误（NoClassDefFoundError）等 。这些异常发生时，Java 虚拟机（JVM）一般会选择线程终止 8.2 throw和throws的区别 throws 用来声明一个方法可能抛出的所有异常信息，表示出现异常的一种可能性，但并不一定会发生这些异常；throw 则是指拋出的一个具体的异常类型，执行 throw 则一定抛出了某种异常对象。 通常在一个方法（类）的声明处通过 throws 声明方法（类）可能拋出的异常信息，而在方法（类）内部通过 throw声明一个具体的异常信息。 throws 通常不用显示地捕获异常，可由系统自动将所有捕获的异常信息抛给上级方法； throw 则需要用户自己捕获相关的异常，而后再对其进行相关包装，最后将包装后的异常信息抛出 8.3 Checked Exception 和 Unchecked Exception Checked Exception 受检查异常 Java 代码在编译过程中，如果受检查异常没有被 catch或者throws 关键字处理的话，就没办法通过编译 常见的受检查异常有： IO 相关的异常、ClassNotFoundException 、SQLException 例如，下面就是 -\rUnchecked Exception 即 不受检查异常 ，Java 代码在编译过程中 ，我们即使不处理不受检查异常也可以正常通过编译。 我们经常看到的有以下几种 NullPointerException ：空指针错误 IllegalArgumentException ：参数错误比如方法入参类型错误 NumberFormatException：字符串转换为数字格式错误 ArrayIndexOutOfBoundsException：数组越界错误 ClassCastException：类型转换错误 ArithmeticException：算术错误 SecurityException ：安全错误比如权限不够 UnsupportedOperationException：不支持的操作错误比如重复创建同一用户 8.4 try-with-resources 与 try-catch-finally try-with-resources 是Java 1.7增加的新语法糖，在try 代码块结束之前会自动关闭资源。 try-with-resources 适用于任何实现 java.lang.AutoCloseable或者 java.io.Closeable 的对象, 字节输入流（InputStream），字节输出流（OutputStream），字符输入流（Reader），字符输出流（Writer）均实现了这接口 try-catch-finally 没有限制条件，finally不仅可以关闭资源，还可以用于执行其他代码块； try-with-resources 代码更加简洁，有限制条件，资源会立即被关闭 finally关闭资源不会立即关闭，取决与网络和系统，可能会很快，也可能会等一两天，所以，最好不要使用finally作为业务流程的控制，在《Effective java》一书 的第9条：try-with-resources优先于try-finally 中有相关详细的介绍，其中提到了许多由于finally延迟导致的网络事件 九、SpringBoot 中优雅的处理统一异常返回 日常开发中，我们处理异常一般都会用到try-catch 、throw和throws 的方式抛出异常。 这种方式不经程序员处理麻烦，对用户来说也不太友好 我们都希望不用写过多的重复代码处理异常，又能提升用户体验。这时候全局异常处理就显得很便捷很重要了\n9.1 全局异常捕获与处理 Springboot对提供了一个 @ControllerAdvice注解以及 @ExceptionHandler注解，分别用于开启全局的异常捕获和说明捕获哪些异常，对那些异常进行处理。\njava\n代码解读\n复制代码\n@ControllerAdvice public class MyExceptionHandler { @ExceptionHandler(value =Exception.class) public String exceptionHandler(Exception e){ System.out.println(\"出现了一个异常\"+e); return e.getMessage(); } }\n分析 上面这段代码就是说，只要是代码运行过程中有异常就会进行捕获，并输出出这个异常。然后我们随便编写一个会发生异常的代码，测试出来的异常是这样的。\n这对于前后端分离来说这样的报错对用户并不好，前后端分离之后唯一的交互就是json了，我们也希望将后端的异常变成json返回给前端处理。\n9.2 用枚举类型记录已知错误信息与成功信息 ErrorEnum枚举类中定义了常见的错误码以及错误的提示信息。 SuccEnum 枚举类中定义了成功码及成功提示信息\n至于这里为什么用枚举就不具体说了，网上文章说说的也比较多了 具体可以参照：Java 枚举(enum) 详解7种常见的用法\n① 已知错误信息\njava\n代码解读\n复制代码\npublic enum ErrorEnum { // 数据操作错误定义 NO_PERMISSION(403,\"没有权限访问\"), NO_AUTH(401,\"请先登录系统\"), NOT_FOUND(404, \"未找到该资源!\"), USER_NOT_FIND(402, \"未找到用户信息\"), INTERNAL_SERVER_ERROR(500, \"服务器出问题了\"), UNKNOW_ERR(-1,\"未知错误\") ; /** 错误码 */ private Integer errorCode; /** 错误信息 */ private String errorMsg; ErrorEnum(Integer errorCode, String errorMsg) { this.errorCode = errorCode; this.errorMsg = errorMsg; } public Integer getErrorCode() { return errorCode; } public String getErrorMsg() { return errorMsg; } }\n② 成功信息\njava\n代码解读\n复制代码\npublic enum SuccEnum { SUCCESS(200, \"success\"); /** 成功码 **/ private Integer succCode; /* 成功信息*/ private String succMsg; SuccEnum(Integer succCode, String succMsg) { this.succCode = succCode; this.succMsg = succMsg; } public Integer getSuccCode() { return succCode; } public String getSuccMsg() { return succMsg; } }\n9.3 定义统一结果返回与异常返回 success：用boolean 类型标识，标识是否成功 code: 状态码，区分各种报错信息与成功返回 msg : 成功或错误提示信息 data : 返回的数据 java\n代码解读\n复制代码\n@Data public class Result { //是否成功 private Boolean success; //状态码 private Integer code; //提示信息 private String msg; //数据 private T data; public Result() { } //自定义返回结果的构造方法 public Result(Boolean success,Integer code, String msg,T data) { this.success = success; this.code = code; this.msg = msg; this.data = data; } }\n9.4 封装工具类返回结果 这里我们定义好了统一的结果返回，其中里面的静态方法是用来当程序异常的时候转换成异常返回规定的格式。\njava\n代码解读\n复制代码\npublic class ResultUtil { //成功，并返回具体数据 public static Result success(SuccEnum succEnum,Object obj){ Result result = new Result(); result.setSuccess(true); result.setMsg(succEnum.getSuccMsg()); result.setCode(succEnum.getSuccCode()); result.setData(obj); return result; } //成功，无数据返回 public static Result succes(SuccEnum succEnum){ Result result = new Result(); result.setSuccess(true); result.setMsg(succEnum.getSuccMsg()); result.setCode(succEnum.getSuccCode()); result.setData(null); return result; } //自定义异常返回的结果 public static Result defineError(DefinitionException de){ Result result = new Result(); result.setSuccess(false); result.setCode(de.getErrorCode()); result.setMsg(de.getErrorMsg()); result.setData(null); return result; } //其他异常处理方法返回的结果 public static Result otherError(ErrorEnum errorEnum){ Result result = new Result(); result.setSuccess(false); result.setMsg(errorEnum.getErrorMsg()); result.setCode(errorEnum.getErrorCode()); result.setData(null); return result; } }\n9.5 自定义异常 内置异常不能满足我们业务需求的时候，我们就需要自定义异常\njava\n代码解读\n复制代码\npublic class DefinitionException extends RuntimeException { protected Integer errorCode; protected String errorMsg; public DefinitionException(){ } public DefinitionException(Integer errorCode, String errorMsg) { this.errorCode = errorCode; this.errorMsg = errorMsg; } public Integer getErrorCode() { return errorCode; } public void setErrorCode(Integer errorCode) { this.errorCode = errorCode; } public String getErrorMsg() { return errorMsg; } public void setErrorMsg(String errorMsg) { this.errorMsg = errorMsg; } }\n9.6 定义全局异常处理类 我们自定义一个全局异常处理类，来处理各种异常,包括自己定义的异常和内部异常。这样可以简化不少代码，不用自己对每个异常都使用try，catch的方式来实现\njava\n代码解读\n复制代码\n@ControllerAdvice public class GlobalExceptionHandler { /** * 处理自定义异常 * */ @ExceptionHandler(value = DefinitionException.class) @ResponseBody public Result bizExceptionHandler(DefinitionException e) { return ResultUtil.defineError(e); } /** * 处理其他异常 * */ @ExceptionHandler(value = Exception.class) @ResponseBody public Result exceptionHandler( Exception e) { return ResultUtil.otherError(ErrorEnum.UNKNOW_ERR); } }\n说明： 方法上面加上一个 @ResponseBody的注解，用于将对象解析成json,方便前后端的交互，也可以使用 @ResponseBody放在异常类上面\n9.7 代码测试 9.7.1 定义User实体类 java\n代码解读\n复制代码\n@Data public class User { //唯一标识id private Integer id; //姓名 private String name; //性别 private String sex; //年龄 private Integer age; }\n9.7.2 定义controller类 java\n代码解读\n复制代码\n@RestController @RequestMapping(\"/result\") public class ExceptionController { @Autowired private GlobalExceptionHandler globalExceptionHandler; @GetMapping(\"/getUser\") public Result getStudent(){ User user = new User(); user.setId(100); user.setName(\"xiezhr\"); user.setAge(21); user.setSex(\"男\"); Result result = ResultUtil.success(SuccEnum.SUCCESS, user); return result; } @GetMapping(\"/getDefException\") public Result DeException(){ throw new DefinitionException(400,\"我出错了\"); } @GetMapping(\"/getException\") public Result Exception(@RequestParam(\"name\") String name, @RequestParam(\"pwd\") String pwd){ Result result = ResultUtil.success(SuccEnum.SUCCESS); try { if (\"admin\".equals(name)){ User user = new User(); user.setId(101); user.setName(\"xiezhr\"); user.setAge(18); user.setSex(\"男\"); result = ResultUtil.success(SuccEnum.SUCCESS,user); }else if (name.equals(\"xiezhr\")){ result = ResultUtil.otherError(ErrorEnum.USER_NOT_FIND); }else{ int i = 1/0; } }catch (Exception e){ result = globalExceptionHandler.exceptionHandler(e); } return result; } }\n9.8 接口测试 9.8.1 获取没有异常的数据返回 http://localhost:8090/result/getUser 9.8.2 自定义异常返回 http://localhost:8090/result/getDefException http://localhost:8090/result/getException?name=xiezhr\u0026pwd=123 9.8.3 其他的异常 返回 http://localhost:8090/result/getException?name=ff\u0026pwd=abc 十、异常处理及规约 异常的处理⽅式有两种。 1、 ⾃⼰处理。 2、 向上抛， 交给调⽤者处理。\n异常， 千万不能捕获了之后什么也不做。 或者只是使⽤e.printStacktrace。\n具体的处理⽅式的选择其实原则⽐较简明： ⾃⼰明确的知道如何处理的， 就要处理掉。 不知道如何处理的， 就交给调⽤者处理。\n下面时阿里巴巴Java开发手册关于异常处理规则\n①【强制】 Java类库中定义的可以通过预检查方式规避的RuntimeException不应该通过catch的方式处理，如NullPointerException、IndexOutOfBoundsException等\n说明：无法通过预检查的异常不在此列，比如当解析字符串形式的数字时，可能存在数字格式错误，通过catch NumberFormatException实现\n正例：\njava\n代码解读\n复制代码\nif(obj!=null){....}\n反例：\njava\n代码解读\n复制代码\ntry{ obj.method(); }catch(NullPointerException e){ ... }\n②【强制】 异常捕获后不要用来做流程控制和条件控制\n说明：异常设计的初衷是解决程序运行中各种意外，且异常的处理效率比条件判断方式要第很多。\n③【强制】 catch 时请分清稳定代码和非稳定代码。稳定代码一般指本机运行且执行结果确定性高的代码。对于非稳定代码的catch 尽可能在进行异常类型的分区后，再做对应的异常处理\n说明：对大段代码进行try-catch,将使程序无法根据不同的异常做出正确的“应激”反应，也不利于定位问题，这是一种不负责的表现\n正例：在用户注册场景中，如果用户输入非法字符串，或用户名称已存在，或用户输入的密码过于简单，那么程序会作出分门别类的判断并提示用户。\n④【强制】 捕获异常使为了处理异常，不要捕获了却说明都不处理而抛弃之，如果不想处理它，请将异常抛给它的调用者。最外层的业务使用者必须处理异常，将其转换为用户可以理解的内容。\n⑤【强制】 在事务场景中，抛出异常被catch 后，如果需要回滚，那么一定要注意手动回滚事务。\n⑥【强制】 finally 块必须对资源对象、流对象进行关闭操作，如果有一次要做try-catch操作。\n说明：对于JDK7即以上版本，可以使用try-catch-resource 方式\n⑦【强制】 不要在finally块中使用return\n说明try 块中return 语句执行成功后，并不马上返回，而是继续执行finally 块中的语句，如果此处存在return语句，则在此直接返回，无情地丢弃try块中的返回点。\n正例：\njava\n代码解读\n复制代码\nprivate int x =0; public int checkReturn(){ try{ //x=1,此处不返回 return ++x; }finally{ //返回的结果是2 return ++x; } }\n⑧【强制】 捕获异常与抛出异常必须完全匹配，或者捕获异常时抛出异常的父类。\n说明：如果以及对方抛出的时绣球，实际接收到的时铅球，就会产生意外\n⑨【强制】 在调用RPC、二方包或动态生成类的相关方法时，捕获异常必须使用Throwable拦截。\n说明：通过反射机制调用方法，如果找不到方法，则抛出NoSuchMethodException。 在说明情况下抛出NoSuchMethodException呢？二方包在类冲突时，仲裁机制可能导致引入非预期的版本使类的方法签名不匹配，或者在字节码修改框架（比如：ASM）动态创建或修改类时，修改了相应的方法签名。对于这些情况，即使在代码编译期是正确的，在代码运行期也会抛出NoSuchMethodException\n⑩【推荐】 方法的返回值可以为null,不强制返回空集合或者空对象等，必须添加注释充分说明在说明情况下会返回null值。此时数据库id不支持存入负数二抛出异常。\n说明：本手册明确，防止产生NPE是调用者的责任。即使被调用方法返回空集合或者空对象，对调用者来说，也并非高枕无忧，必须考虑远程调用失败、序列化失败、运行时异常等场景返回null值的情况\n⑪【推荐】 防止产生NPE时程序员的基本修养，注意NPE产生的场景。 1）当返回类型为基本数据类型，return 包装数据类型的对象时，自动拆箱有可能产生NPE 反例：\njava\n代码解读\n复制代码\npublic int f(){ //如果为null,则自动拆箱，抛NPE。 return Integer 对象; }\n2）数据库的查询结果可能为null 3) 集合里的元素即使isNotEmpty , 取出的数据元素也有可能为null\n当远程调用返回对象时，一律要求进行空指针判断，以防止产生NPE。 5）对于Session 中获取的数据，建议进行NPE检查，以避免空指针 6）级联调用obj.getA().getB().getC();的一连串调用容易产生NPE。 ⑫【推荐】 定义时区分 unchecked/checked 异常，避免直接抛出new RuntimeException(),更不允许抛出Exception 或者Throwable，应该使用业务含义的自定义异常。推荐业界已定义过的自定义异常，如：DAOException / ServiceException 等\n⑬ 【参考】 对于公司外的HTTP/API 开放接口，必须使用“errorCode”:应用内部推荐异常抛出； 跨应用间RPC调用优先考虑使用Result 方式，封装isSuccess() 方法、errorCode 和errorMessage。\n说明：关于RPC方法返回方式使用Result方式的理由 1）使用抛出异常返回方式，调用方式如果没有捕获到，就会产生运行时错误 2）如果不加栈信息，知识new自定义异常，加入自己理解的errorMesage，对于调用解决问题的帮助不会太多。如果加了栈信息，在频繁调用出错的情况下，数据序列化和传输的性能损耗也是问题。\n⑭【参考】 避免出现重复的代码（Don't Repeat Yourself）,即DRY原则\n说明： 随意复制和粘贴代码，必然导致代码的重复，当以后需要修改时，需要修改所有的副本，容易遗漏。必要时抽取共性方法或公共类，甚至将代码组件化。\n正例： 一个类中由多个public 方法，都需要进行数行相同的参数校验操作，这个时候请抽取：\njava\n代码解读\n复制代码\nprivate boolean checkParam(DTO dto){...}\n本期内容到这就结束了，各位小伙伴们，我们下期见 (●’◡’●)\n",
  "wordCount" : "1975",
  "inLanguage": "zh",
  "image": "http://localhost:1313/images/papermod-cover.png","datePublished": "2023-07-09T00:00:00Z",
  "dateModified": "2023-07-09T00:00:00Z",
  "author":{
    "@type": "Person",
    "name": "程序员晓凡"
  },
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "http://localhost:1313/posts/juejin/%E5%95%AA%E8%BF%98%E6%95%A2%E6%8A%9B%E5%87%BA%E5%BC%82%E5%B8%B8/"
  },
  "publisher": {
    "@type": "Organization",
    "name": "PaperMod",
    "logo": {
      "@type": "ImageObject",
      "url": "http://localhost:1313/%3Clink%20/%20abs%20url%3E"
    }
  }
}
</script>
</head>

<body class=" dark" id="top">
<script>
    if (localStorage.getItem("pref-theme") === "light") {
        document.body.classList.remove('dark')
    }

</script>

<header class="header">
    <nav class="nav">
        <div class="logo">
            <a href="http://localhost:1313/" accesskey="h" title="Home (Alt + H)">
                        
                    <img src="http://localhost:1313/images/msg_hu15231257772499651944.png" alt="" aria-label="logo"
                        height="20">Home</a>
            <div class="logo-switches">
                <button id="theme-toggle" accesskey="t" title="(Alt + T)">
                    <svg id="moon" xmlns="http://www.w3.org/2000/svg" width="24" height="18" viewBox="0 0 24 24"
                        fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                        stroke-linejoin="round">
                        <path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"></path>
                    </svg>
                    <svg id="sun" xmlns="http://www.w3.org/2000/svg" width="24" height="18" viewBox="0 0 24 24"
                        fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                        stroke-linejoin="round">
                        <circle cx="12" cy="12" r="5"></circle>
                        <line x1="12" y1="1" x2="12" y2="3"></line>
                        <line x1="12" y1="21" x2="12" y2="23"></line>
                        <line x1="4.22" y1="4.22" x2="5.64" y2="5.64"></line>
                        <line x1="18.36" y1="18.36" x2="19.78" y2="19.78"></line>
                        <line x1="1" y1="12" x2="3" y2="12"></line>
                        <line x1="21" y1="12" x2="23" y2="12"></line>
                        <line x1="4.22" y1="19.78" x2="5.64" y2="18.36"></line>
                        <line x1="18.36" y1="5.64" x2="19.78" y2="4.22"></line>
                    </svg>
                </button>
            </div>
        </div>
        <ul id="menu">
            <li>
                <a href="http://localhost:1313/archives" title="Archive">
                    <span>Archive</span>
                </a>
            </li>
            <li>
                <a href="http://localhost:1313/search/" title="Search (Alt &#43; /)" accesskey=/>
                    <span>Search</span>
                </a>
            </li>
            <li>
                <a href="http://localhost:1313/tags/" title="Tags">
                    <span>Tags</span>
                </a>
            </li>
            <li>
                <a href="https://github.com/adityatelange/hugo-PaperMod/wiki/" title="WiKi">
                    <span>WiKi</span>&nbsp;
                    <svg fill="none" shape-rendering="geometricPrecision" stroke="currentColor" stroke-linecap="round"
                        stroke-linejoin="round" stroke-width="2.5" viewBox="0 0 24 24" height="12" width="12">
                        <path d="M18 13v6a2 2 0 01-2 2H5a2 2 0 01-2-2V8a2 2 0 012-2h6"></path>
                        <path d="M15 3h6v6"></path>
                        <path d="M10 14L21 3"></path>
                    </svg>
                </a>
            </li>
        </ul>
    </nav>
</header>
<main class="main">

<article class="post-single">
  <header class="post-header">
    <div class="breadcrumbs"><a href="http://localhost:1313/">主页</a>&nbsp;»&nbsp;<a href="http://localhost:1313/posts/">Posts</a></div>
    <h1 class="post-title entry-hint-parent">
      啪，还敢抛出异常
    </h1>
    <div class="post-description">
      Java异常处理是Java编程中非常重要的一部分。本文简要介绍了异常的概念和Java中的异常处理机制。通过学习本文，您将了解如何使用try-catch语句捕获和处理异常，以及如何使用throws关键字
    </div>
    <div class="post-meta"><span title='2023-07-09 00:00:00 +0000 UTC'>七月 9, 2023</span>&nbsp;·&nbsp;10 分钟&nbsp;·&nbsp;程序员晓凡&nbsp;|&nbsp;<a href="https://github.com/WangShaoyu1/myBlogPaperMod/tree/master/content/posts/jueJin/%e5%95%aa%ef%bc%8c%e8%bf%98%e6%95%a2%e6%8a%9b%e5%87%ba%e5%bc%82%e5%b8%b8.md" rel="noopener noreferrer" target="_blank">Suggest Changes</a>

</div>
  </header> <div class="toc">
    <details >
        <summary accesskey="c" title="(Alt + C)">
            <span class="details">目录</span>
        </summary>

        <div class="inner"><ul>
                <li>
                    <a href="#%e5%89%8d%e8%a8%80" aria-label="前言">前言</a></li>
                <li>
                    <a href="#%e4%b8%80%e5%bc%82%e5%b8%b8%e5%bc%95%e5%85%a5" aria-label="一、异常引入">一、异常引入</a></li>
                <li>
                    <a href="#%e4%ba%8c%e5%9f%ba%e6%9c%ac%e6%a6%82%e5%bf%b5" aria-label="二、基本概念">二、基本概念</a></li>
                <li>
                    <a href="#%e4%b8%89%e5%bc%82%e5%b8%b8%e7%bb%a7%e6%89%bf%e4%bd%93%e7%b3%bb" aria-label="三、异常继承体系">三、异常继承体系</a></li>
                <li>
                    <a href="#%e5%9b%9b%e5%b8%b8%e8%a7%81%e8%bf%90%e8%a1%8c%e5%bc%82%e5%b8%b8" aria-label="四、常见运行异常">四、常见运行异常</a><ul>
                        
                <li>
                    <a href="#41-nullpointerexception-%e7%a9%ba%e6%8c%87%e9%92%88%e5%bc%82%e5%b8%b8" aria-label="4.1 NullPointerException 空指针异常">4.1 NullPointerException 空指针异常</a></li>
                <li>
                    <a href="#42-arithmeticexception-%e6%95%b0%e5%ad%a6%e8%bf%90%e7%ae%97%e5%bc%82%e5%b8%b8" aria-label="4.2 ArithmeticException 数学运算异常">4.2 ArithmeticException 数学运算异常</a></li>
                <li>
                    <a href="#43-arrayindexoutofboundsexception-%e6%95%b0%e7%bb%84%e4%b8%8b%e6%a0%87%e8%b6%8a%e7%95%8c%e5%bc%82%e5%b8%b8" aria-label="4.3 ArrayIndexOutOfBoundsException 数组下标越界异常">4.3 ArrayIndexOutOfBoundsException 数组下标越界异常</a></li>
                <li>
                    <a href="#44-classcastexception-%e7%b1%bb%e5%9e%8b%e8%bd%ac%e6%8d%a2%e5%bc%82%e5%b8%b8" aria-label="4.4 ClassCastException 类型转换异常">4.4 ClassCastException 类型转换异常</a></li>
                <li>
                    <a href="#45-numberformatexception-%e6%95%b0%e5%ad%97%e6%a0%bc%e5%bc%8f%e4%b8%8d%e6%ad%a3%e7%a1%ae%e5%bc%82%e5%b8%b8" aria-label="4.5 NumberFormatException 数字格式不正确异常">4.5 NumberFormatException 数字格式不正确异常</a></li></ul>
                </li>
                <li>
                    <a href="#%e4%ba%94%e5%b8%b8%e8%a7%81%e7%bc%96%e8%af%91%e6%97%b6%e5%bc%82%e5%b8%b8" aria-label="五、常见编译时异常">五、常见编译时异常</a><ul>
                        
                <li>
                    <a href="#51-filenotfoundexception-%e6%93%8d%e4%bd%9c%e4%b8%80%e4%b8%aa%e4%b8%8d%e5%ad%98%e5%9c%a8%e7%9a%84%e6%96%87%e4%bb%b6%e6%97%b6%e5%80%99%e5%8f%91%e7%94%9f%e5%bc%82%e5%b8%b8" aria-label="5.1 FileNotFoundException 操作一个不存在的文件时候发生异常">5.1 FileNotFoundException 操作一个不存在的文件时候发生异常</a></li>
                <li>
                    <a href="#52-classnotfoundexception-%e5%8a%a0%e8%bd%bd%e7%b1%bb%e7%b1%bb%e4%b8%8d%e5%ad%98%e5%9c%a8%e6%97%b6%e5%bc%82%e5%b8%b8" aria-label="5.2 ClassNotFoundException 加载类，类不存在时异常">5.2 ClassNotFoundException 加载类，类不存在时异常</a></li>
                <li>
                    <a href="#53-sqlexception-%e6%93%8d%e4%bd%9c%e6%95%b0%e6%8d%ae%e5%ba%93%e6%9f%a5%e8%af%a2%e8%a1%a8%e6%97%b6%e5%8f%91%e7%94%9f%e5%bc%82%e5%b8%b8" aria-label="5.3 SQLException 操作数据库，查询表时发生异常">5.3 SQLException 操作数据库，查询表时发生异常</a></li>
                <li>
                    <a href="#54-illegalargumentexception-%e5%8f%82%e6%95%b0%e4%b8%8d%e5%8c%b9%e9%85%8d%e6%97%b6%e5%8f%91%e7%94%9f%e5%bc%82%e5%b8%b8" aria-label="5.4 IllegalArgumentException 参数不匹配时发生异常">5.4 IllegalArgumentException 参数不匹配时发生异常</a></li></ul>
                </li>
                <li>
                    <a href="#%e5%85%ad%e5%bc%82%e5%b8%b8%e5%a4%84%e7%90%86" aria-label="六、异常处理">六、异常处理</a><ul>
                        
                <li>
                    <a href="#61-%e5%bc%82%e5%b8%b8%e5%a4%84%e7%90%86%e6%96%b9%e5%bc%8f" aria-label="6.1 异常处理方式">6.1 异常处理方式</a></li>
                <li>
                    <a href="#62-%e5%bc%82%e5%b8%b8%e5%a4%84%e7%90%86" aria-label="6.2 异常处理">6.2 异常处理</a><ul>
                        
                <li>
                    <a href="#621-try-catch-finally" aria-label="6.2.1 try-catch-finally">6.2.1 try-catch-finally</a></li>
                <li>
                    <a href="#622-try-with-resources" aria-label="6.2.2 try-with-resources">6.2.2 try-with-resources</a></li>
                <li>
                    <a href="#623-%e6%8a%9b%e5%87%ba%e5%bc%82%e5%b8%b8" aria-label="6.2.3 抛出异常">6.2.3 抛出异常</a><ul>
                        
                <li>
                    <a href="#6231-thorows" aria-label="6.2.3.1 thorows">6.2.3.1 thorows</a></li>
                <li>
                    <a href="#6231-throw" aria-label="6.2.3.1 throw">6.2.3.1 throw</a></li></ul>
                </li>
                <li>
                    <a href="#624-%e8%87%aa%e5%ae%9a%e4%b9%89%e5%bc%82%e5%b8%b8" aria-label="6.2.4 自定义异常">6.2.4 自定义异常</a></li></ul>
                </li>
                <li>
                    <a href="#625-%e5%a4%9a%e5%bc%82%e5%b8%b8%e6%8d%95%e8%8e%b7" aria-label="6.2.5 多异常捕获">6.2.5 多异常捕获</a></li></ul>
                </li>
                <li>
                    <a href="#%e4%b8%83throwable-%e7%b1%bb%e5%b8%b8%e7%94%a8%e6%96%b9%e6%b3%95" aria-label="七、Throwable 类常用方法">七、Throwable 类常用方法</a></li>
                <li>
                    <a href="#%e5%85%ab%e6%98%93%e6%b7%b7%e6%a6%82%e5%bf%b5" aria-label="八、易混概念">八、易混概念</a><ul>
                        
                <li>
                    <a href="#81-error%e5%92%8cexception%e7%9a%84%e5%bc%82%e5%90%8c" aria-label="8.1 Error和Exception的异同">8.1 Error和Exception的异同</a></li>
                <li>
                    <a href="#82-throw%e5%92%8cthrows%e7%9a%84%e5%8c%ba%e5%88%ab" aria-label="8.2 throw和throws的区别">8.2 throw和throws的区别</a></li>
                <li>
                    <a href="#83-checked-exception-%e5%92%8c-unchecked-exception" aria-label="8.3 Checked Exception 和 Unchecked Exception">8.3 Checked Exception 和 Unchecked Exception</a></li>
                <li>
                    <a href="#84-try-with-resources-%e4%b8%8e-try-catch-finally" aria-label="8.4 try-with-resources 与 try-catch-finally">8.4 try-with-resources 与 try-catch-finally</a></li></ul>
                </li>
                <li>
                    <a href="#%e4%b9%9dspringboot-%e4%b8%ad%e4%bc%98%e9%9b%85%e7%9a%84%e5%a4%84%e7%90%86%e7%bb%9f%e4%b8%80%e5%bc%82%e5%b8%b8%e8%bf%94%e5%9b%9e" aria-label="九、SpringBoot 中优雅的处理统一异常返回">九、SpringBoot 中优雅的处理统一异常返回</a><ul>
                        
                <li>
                    <a href="#91-%e5%85%a8%e5%b1%80%e5%bc%82%e5%b8%b8%e6%8d%95%e8%8e%b7%e4%b8%8e%e5%a4%84%e7%90%86" aria-label="9.1 全局异常捕获与处理">9.1 全局异常捕获与处理</a></li>
                <li>
                    <a href="#92-%e7%94%a8%e6%9e%9a%e4%b8%be%e7%b1%bb%e5%9e%8b%e8%ae%b0%e5%bd%95%e5%b7%b2%e7%9f%a5%e9%94%99%e8%af%af%e4%bf%a1%e6%81%af%e4%b8%8e%e6%88%90%e5%8a%9f%e4%bf%a1%e6%81%af" aria-label="9.2 用枚举类型记录已知错误信息与成功信息">9.2 用枚举类型记录已知错误信息与成功信息</a></li>
                <li>
                    <a href="#93-%e5%ae%9a%e4%b9%89%e7%bb%9f%e4%b8%80%e7%bb%93%e6%9e%9c%e8%bf%94%e5%9b%9e%e4%b8%8e%e5%bc%82%e5%b8%b8%e8%bf%94%e5%9b%9e" aria-label="9.3 定义统一结果返回与异常返回">9.3 定义统一结果返回与异常返回</a></li>
                <li>
                    <a href="#94-%e5%b0%81%e8%a3%85%e5%b7%a5%e5%85%b7%e7%b1%bb%e8%bf%94%e5%9b%9e%e7%bb%93%e6%9e%9c" aria-label="9.4 封装工具类返回结果">9.4 封装工具类返回结果</a></li>
                <li>
                    <a href="#95-%e8%87%aa%e5%ae%9a%e4%b9%89%e5%bc%82%e5%b8%b8" aria-label="9.5 自定义异常">9.5 自定义异常</a></li>
                <li>
                    <a href="#96-%e5%ae%9a%e4%b9%89%e5%85%a8%e5%b1%80%e5%bc%82%e5%b8%b8%e5%a4%84%e7%90%86%e7%b1%bb" aria-label="9.6 定义全局异常处理类">9.6 定义全局异常处理类</a></li>
                <li>
                    <a href="#97-%e4%bb%a3%e7%a0%81%e6%b5%8b%e8%af%95" aria-label="9.7 代码测试">9.7 代码测试</a><ul>
                        
                <li>
                    <a href="#971-%e5%ae%9a%e4%b9%89user%e5%ae%9e%e4%bd%93%e7%b1%bb" aria-label="9.7.1 定义User实体类">9.7.1 定义User实体类</a></li>
                <li>
                    <a href="#972-%e5%ae%9a%e4%b9%89controller%e7%b1%bb" aria-label="9.7.2 定义controller类">9.7.2 定义controller类</a></li></ul>
                </li>
                <li>
                    <a href="#98-%e6%8e%a5%e5%8f%a3%e6%b5%8b%e8%af%95" aria-label="9.8 接口测试">9.8 接口测试</a><ul>
                        
                <li>
                    <a href="#981-%e8%8e%b7%e5%8f%96%e6%b2%a1%e6%9c%89%e5%bc%82%e5%b8%b8%e7%9a%84%e6%95%b0%e6%8d%ae%e8%bf%94%e5%9b%9e" aria-label="9.8.1 获取没有异常的数据返回">9.8.1 获取没有异常的数据返回</a></li>
                <li>
                    <a href="#982-%e8%87%aa%e5%ae%9a%e4%b9%89%e5%bc%82%e5%b8%b8%e8%bf%94%e5%9b%9e" aria-label="9.8.2 自定义异常返回">9.8.2 自定义异常返回</a></li>
                <li>
                    <a href="#983-%e5%85%b6%e4%bb%96%e7%9a%84%e5%bc%82%e5%b8%b8-%e8%bf%94%e5%9b%9e" aria-label="9.8.3 其他的异常 返回">9.8.3 其他的异常 返回</a></li></ul>
                </li></ul>
                </li>
                <li>
                    <a href="#%e5%8d%81%e5%bc%82%e5%b8%b8%e5%a4%84%e7%90%86%e5%8f%8a%e8%a7%84%e7%ba%a6" aria-label="十、异常处理及规约">十、异常处理及规约</a>
                </li>
            </ul>
        </div>
    </details>
</div>

  <div class="post-content"><h3 id="前言">前言<a hidden class="anchor" aria-hidden="true" href="#前言">#</a></h3>
<p>去年又重新刷了路遥的《平凡的世界》，最近也在朋友推荐下，来看了路遥的另一部成名作《人生》。 故事中的主人公高加林，虽生在农村，面朝黄土背朝天，却不甘心像父辈一样或者，一心想着摆脱民语的束缚，追求他的理想生活。 然而命运多舛，在他所想象的理想生活中，一次次跌倒，最终不得不承认自己的平凡，生活总得继续。 现实世界如此，代码世界里，我们也希望一切都是理想的。 我们希望用户输入的数据格式永远是正确的，打开的资源也一定存在，用户的硬件是正常的，用户的操作系统四稳定的，用户的网络也一定是畅通的等等 <img loading="lazy" src="https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/660e5184fdba4762a6522f48aa5ed40c~tplv-k3u1fbpfcp-zoom-in-crop-mark:1512:0:0:0.awebp" alt="还敢抛异常"  />
 然而事与愿违，愿望是好的，现实是残酷的。 引入异常机制的目的就在于，当“人生”中出现异常时，能够将其捕获并处理，保证我们能更好的走下去，不至于出现一点插曲，就停滞不前。</p>
<h3 id="一异常引入">一、异常引入<a hidden class="anchor" aria-hidden="true" href="#一异常引入">#</a></h3>
<p>因此呢就出现了异常处理，我们把可能出现异常的业务代码放到try块中定义，把异常处理放到catch块中进行处理，保证程序遇到异常依然能继续运行，保证程序的健壮性。</p>
<p>① 我们来看看高加林的一生中各种异常的处理</p>
<p>java</p>
<p>代码解读</p>
<p>复制代码</p>
<p><code>try{ 	//业务逻辑，高加林的一生 	System.out.println(&quot;1、高中毕业，虽然没考上大学。却不断学习，在报纸上发表诗歌和散文，参加考试，谋得一份临时教师职位&quot;); 	System.out.println(&quot;2、高加林的叔叔从外地回到家乡工作，在县城担任劳动局局长,副局长为了讨好新上任的局长;&quot;); 	System.out.println(&quot;便私下给高加林走了后门，就这样高加林成为了公职人员&quot;); 	System.out.println(&quot;3、与高中同学黄亚萍相遇，再次相遇的两个人，志趣相投，相聊甚欢。高加林以为攀上黄亚萍这个高枝，能到大城市一展宏图&quot;); }catch(ExceptionClass1 e1){ 	System.out.println(&quot;第一个异常发生，教师职位被他人顶替&quot;); 	System.out.println(&quot;没有了工作，重新回到农村，成为最不想当的农民&quot;); 	System.out.println(&quot;很快加入村里的劳动队伍里，白天努力劳作，晚上看书学习，等待着东山再起的机会&quot;); }catch(ExceptionClass2 e2){ 	System.out.println(&quot;第二个异常发生，遭人举报走后门&quot;); 	System.out.println(&quot;再次丢了工作，一直想摆脱农名身份的他，再次成为了农民&quot;); }catch(ExceptionClass3 e3){ 	System.out.println(&quot;第三个异常发生，纸包不住火，黄亚萍及其家人知道了高加林遭遇举报&quot;); 	System.out.println(&quot;被打回原型，和黄亚萍断绝了关系&quot;); 	System.out.println(&quot;黄亚萍不想高加林回农村，希望高加林去找叔父帮忙，看是否可以继续留下来&quot;); }catch(Exception e){ 	System.out.println(&quot;再次跌倒的他，没再去找叔父&quot;); 	System.out.println(&quot;有了清醒的认知，自己的路还是得靠自己走下去&quot;); }finally{ 	System.out.println(&quot;接受现实，更好的走下去&quot;); }</code></p>
<p>② 代码中</p>
<p>java</p>
<p>代码解读</p>
<p>复制代码</p>
<p><code>//未处理异常，程序遇到异常没法继续执行 public class ExceptionTest {     public static void main(String[] args) {         int num1 =7;         int num2 =0;         int res = num1/num2;         System.out.println(&quot;程序继续执行......&quot;);     } } //输出 Exception in thread &quot;main&quot; java.lang.ArithmeticException: / by zero 	at ExceptionTest.main(ExceptionTest.java:5)</code></p>
<p>加入异常处理</p>
<p>java</p>
<p>代码解读</p>
<p>复制代码</p>
<p><code>//加入异常处理，程序遇到异常后继续运行 public class ExceptionTest {     public static void main(String[] args) {         int num1 =7;         int num2 =0;         try {             int res = num1/num2;         } catch (Exception e) {             System.out.println(e.getMessage());         }         System.out.println(&quot;程序继续执行......&quot;);     } } //输出 / by zero 程序继续执行......</code></p>
<p><strong>小结：</strong> 如果执行try块里的业务逻辑代码出现异常，系统会自动生成一个异常对象，该异常对象被体骄傲给Java运行时环境，这个过程成为抛出异常 Java运行时环境收到异常对象时，会寻找能处理异常对象的catch块，如果找到合适的catch块，则把该异常对象交给该catch块处理，这个过程被成为异常捕获； 如果Java运行环境找不到捕获异常的catch块，则运行时环境终止，Java程序已将退出</p>
<h3 id="二基本概念">二、基本概念<a hidden class="anchor" aria-hidden="true" href="#二基本概念">#</a></h3>
<blockquote>
<p>程序执行中发生的不正常情况（语法错误逻辑错误不是异常）称为异常，所有的异常都继承与<code>java.lang.Throwable</code> 。<code>Throwable</code> 有两个重要子类</p>
</blockquote>
<ul>
<li>Error(错误)：Java虚拟机无法解决的严重问题，我们没办法通过 catch 来进行捕获 。如：内存溢出（<code>OutOfMemoryError</code>）、Java 虚拟机运行错误（<code>Virtual MachineError</code>）、类定义错误（<code>NoClassDefFoundError</code>）等。error 是严重错误，Java虚拟机会选择线程终止</li>
<li>Exception(异常)：编程错误或偶尔的外在因素导致的一般问题，程序本身可以处理的异常，可以通过 <code>catch</code> 来进行捕获。<code>Exception</code> 又可以分 <strong>运行时异常</strong>（程序运行时发生的异常）和<strong>编译时异常</strong>（程序编译期间产生的异常，必须要处理的异常，否则代码没法编译通过）。</li>
</ul>
<p><img loading="lazy" src="https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/16fd92ea196a439581b75c00867602af~tplv-k3u1fbpfcp-zoom-in-crop-mark:1512:0:0:0.awebp" alt="在这里插入图片描述"  />
</p>
<h3 id="三异常继承体系">三、异常继承体系<a hidden class="anchor" aria-hidden="true" href="#三异常继承体系">#</a></h3>
<p><strong>注</strong>：虚线为实现，实线为继承 <img loading="lazy" src="https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/42026781bdbb40d3976fec722c4b4528~tplv-k3u1fbpfcp-zoom-in-crop-mark:1512:0:0:0.awebp" alt="在这里插入图片描述"  />
</p>
<h3 id="四常见运行异常">四、常见运行异常<a hidden class="anchor" aria-hidden="true" href="#四常见运行异常">#</a></h3>
<h4 id="41-nullpointerexception-空指针异常">4.1 NullPointerException 空指针异常<a hidden class="anchor" aria-hidden="true" href="#41-nullpointerexception-空指针异常">#</a></h4>
<p><img loading="lazy" src="https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/b92bcfc1a51e458388126edca2de651a~tplv-k3u1fbpfcp-zoom-in-crop-mark:1512:0:0:0.awebp" alt="在这里插入图片描述"  />
</p>
<p>java</p>
<p>代码解读</p>
<p>复制代码</p>
<p><code>public class ExceptionTest {     public static void main(String[] args) {        String str = null;         System.out.println(str.length());     } } //输出 Exception in thread &quot;main&quot; java.lang.NullPointerException 	at ExceptionTest.main(ExceptionTest.java:4)</code></p>
<h4 id="42-arithmeticexception-数学运算异常">4.2 ArithmeticException 数学运算异常<a hidden class="anchor" aria-hidden="true" href="#42-arithmeticexception-数学运算异常">#</a></h4>
<p><img loading="lazy" src="https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/a10d9a42fe3646eeb4069f0a79c5cb04~tplv-k3u1fbpfcp-zoom-in-crop-mark:1512:0:0:0.awebp" alt="在这里插入图片描述"  />
</p>
<p>java</p>
<p>代码解读</p>
<p>复制代码</p>
<p><code>public class ExceptionTest {     public static void main(String[] args) {       int num1=7;       int num2=0;       int res = num1/num2;     } } //输出 Exception in thread &quot;main&quot; java.lang.ArithmeticException: / by zero 	at ExceptionTest.main(ExceptionTest.java:5)</code></p>
<h4 id="43-arrayindexoutofboundsexception-数组下标越界异常">4.3 ArrayIndexOutOfBoundsException 数组下标越界异常<a hidden class="anchor" aria-hidden="true" href="#43-arrayindexoutofboundsexception-数组下标越界异常">#</a></h4>
<p><img loading="lazy" src="https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/24bca4dddd6041cfa483b7b6b1380e0b~tplv-k3u1fbpfcp-zoom-in-crop-mark:1512:0:0:0.awebp" alt="在这里插入图片描述"  />
</p>
<p>java</p>
<p>代码解读</p>
<p>复制代码</p>
<p><code>public class ExceptionTest {     public static void main(String[] args) {       String strarr[] ={&quot;个人博客&quot;,&quot;www.xiezhrspace.cn&quot;,&quot;公众号&quot;,&quot;XiezhrSpace&quot;};         //注意数组下标时从0开始的         for (int i = 0; i &lt;= strarr.length; i++) {             System.out.println(strarr[i]);         }     } } //输出 个人博客 www.xiezhrspace.cn 公众号 XiezhrSpace Exception in thread &quot;main&quot; java.lang.ArrayIndexOutOfBoundsException: 4 	at ExceptionTest.main(ExceptionTest.java:5)</code></p>
<h4 id="44-classcastexception-类型转换异常">4.4 ClassCastException 类型转换异常<a hidden class="anchor" aria-hidden="true" href="#44-classcastexception-类型转换异常">#</a></h4>
<p><img loading="lazy" src="https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/f63ee8b94427448594f6825425e9c589~tplv-k3u1fbpfcp-zoom-in-crop-mark:1512:0:0:0.awebp" alt="在这里插入图片描述"  />
</p>
<p>java</p>
<p>代码解读</p>
<p>复制代码</p>
<p><code>public class ExceptionTest {     public static void main(String[] args) {         Class1 class1 = new Class2();  //向上转型         Class2 class2 = (Class2)class1; //向下转型         Class3 class3= (Class3)class1;  //两个类没有关系，转型失败     } } class Class1{} class Class2 extends Class1{}; class Class3 extends Class1{}; //输出 Exception in thread &quot;main&quot; java.lang.ClassCastException: Class2 cannot be cast to Class3 	at ExceptionTest.main(ExceptionTest.java:5)</code></p>
<h4 id="45-numberformatexception-数字格式不正确异常">4.5 NumberFormatException 数字格式不正确异常<a hidden class="anchor" aria-hidden="true" href="#45-numberformatexception-数字格式不正确异常">#</a></h4>
<p><img loading="lazy" src="https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/a4eaec3d595e4dbc862293af4ec216c9~tplv-k3u1fbpfcp-zoom-in-crop-mark:1512:0:0:0.awebp" alt="在这里插入图片描述"  />
</p>
<p>java</p>
<p>代码解读</p>
<p>复制代码</p>
<p><code>public class ExceptionTest {     public static void main(String[] args) {       String str1 =&quot;123&quot;;       String str2 = &quot;abc&quot;;         System.out.println(Integer.valueOf(str1));   //可以转成功         System.out.println(Integer.valueOf(str2));     } } //输出 123 Exception in thread &quot;main&quot; java.lang.NumberFormatException: For input string: &quot;abc&quot; 	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) 	at java.lang.Integer.parseInt(Integer.java:580) 	at java.lang.Integer.valueOf(Integer.java:766) 	at ExceptionTest.main(ExceptionTest.java:6)</code></p>
<h3 id="五常见编译时异常">五、常见编译时异常<a hidden class="anchor" aria-hidden="true" href="#五常见编译时异常">#</a></h3>
<blockquote>
<p>编译期间就必须处理的异常，否则代码不能通过编译 <img loading="lazy" src="https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/b62bc4320ce0462393b3b9832a8386b9~tplv-k3u1fbpfcp-zoom-in-crop-mark:1512:0:0:0.awebp" alt="在这里插入图片描述"  />
</p>
</blockquote>
<h4 id="51-filenotfoundexception-操作一个不存在的文件时候发生异常">5.1 FileNotFoundException 操作一个不存在的文件时候发生异常<a hidden class="anchor" aria-hidden="true" href="#51-filenotfoundexception-操作一个不存在的文件时候发生异常">#</a></h4>
<p><img loading="lazy" src="https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/81a28c1692944ea2a174dcdec043f94d~tplv-k3u1fbpfcp-zoom-in-crop-mark:1512:0:0:0.awebp" alt="在这里插入图片描述"  />
</p>
<h4 id="52-classnotfoundexception-加载类类不存在时异常">5.2 ClassNotFoundException 加载类，类不存在时异常<a hidden class="anchor" aria-hidden="true" href="#52-classnotfoundexception-加载类类不存在时异常">#</a></h4>
<p><img loading="lazy" src="https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/79231dc03dca4c7aa7ab1c95d81a1226~tplv-k3u1fbpfcp-zoom-in-crop-mark:1512:0:0:0.awebp" alt="在这里插入图片描述"  />
</p>
<h4 id="53-sqlexception-操作数据库查询表时发生异常">5.3 SQLException 操作数据库，查询表时发生异常<a hidden class="anchor" aria-hidden="true" href="#53-sqlexception-操作数据库查询表时发生异常">#</a></h4>
<p><img loading="lazy" src="https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/3c20623c6be54e13a5116c118b832a25~tplv-k3u1fbpfcp-zoom-in-crop-mark:1512:0:0:0.awebp" alt="在这里插入图片描述"  />
</p>
<h4 id="54-illegalargumentexception-参数不匹配时发生异常">5.4 IllegalArgumentException 参数不匹配时发生异常<a hidden class="anchor" aria-hidden="true" href="#54-illegalargumentexception-参数不匹配时发生异常">#</a></h4>
<p><img loading="lazy" src="https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/f31f281ad6c640098e9c2e9de49e92aa~tplv-k3u1fbpfcp-zoom-in-crop-mark:1512:0:0:0.awebp" alt="在这里插入图片描述"  />
</p>
<h3 id="六异常处理">六、异常处理<a hidden class="anchor" aria-hidden="true" href="#六异常处理">#</a></h3>
<blockquote>
<p>Java 的异常处理通过 5 个关键字来实现：<code>try</code>、<code>catch</code>、<code>throw</code>、<code>throws</code> 和<code>finally</code>。 <code>try catch</code> 语句用于捕获并自行处理异常 <code>finally</code> 语句用于在任何情况下（除特殊情况外）都必须执行的代码 <code>throw</code> 手动生成异常对象 <code>throws</code> 将发生的异常抛出，交给调用者处理，最顶级的处理者是<code>JVM</code></p>
</blockquote>
<h4 id="61-异常处理方式">6.1 异常处理方式<a hidden class="anchor" aria-hidden="true" href="#61-异常处理方式">#</a></h4>
<ul>
<li>try-catch-finally :在代码中捕获异常自行处理</li>
<li>throws ：将发生的异常抛出，交给调用者处理，最顶级处理者是<code>JVM</code></li>
</ul>
<p><strong>注：</strong> try-catch-finally 和throws 任选一种即可</p>
<h4 id="62-异常处理">6.2 异常处理<a hidden class="anchor" aria-hidden="true" href="#62-异常处理">#</a></h4>
<h5 id="621-try-catch-finally">6.2.1 try-catch-finally<a hidden class="anchor" aria-hidden="true" href="#621-try-catch-finally">#</a></h5>
<p>①原理图 <img loading="lazy" src="https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/fecf42095bf74ecaa63a24896882bf46~tplv-k3u1fbpfcp-zoom-in-crop-mark:1512:0:0:0.awebp" alt="在这里插入图片描述"  />
 ②语法结构</p>
<p>java</p>
<p>代码解读</p>
<p>复制代码</p>
<p><code>try {     逻辑程序块  //可能有异常的代码 } catch(Exception e) { 	/* 	①发生异常时，系统将异常封装成Exception对象e，并传递给catch 	②得到异常Exception e 后，程序员自行处理 	注：只有发生异常时候，catch代码块才执行     */     捕获异常     throw(e);   } finally {     释放资源代码块 }</code></p>
<p>③实例 <strong>小提示：选中代码，按下快捷键ctrl+alt+t 可以呼出代码提示</strong></p>
<p>java</p>
<p>代码解读</p>
<p>复制代码</p>
<p><code>public class TestException {     public static void main(String[] args) {         int num1 =10;         int num2 =0;         try {             int num3=num1/num2;         }catch (Exception e){             e.printStackTrace();         }finally {             System.out.println(&quot;finally代码块被执行了&quot;);         }         System.out.println(&quot;程序继续执行...&quot;);     } } //输出 java.lang.ArithmeticException: / by zero 	at com.xiezhr.TestException.main(TestException.java:9) finally代码块被执行了 程序继续执行...</code></p>
<p>上述代码中，把可能出现异常的代码<code>num1/num2;</code> 放到了try语句块中，当代码发生异常时，在catch中捕获异常，并打印异常。不管有没有发生异常，<code>finally</code> 语句块里的代码都会执行。发生异常后程序并没有终止，最后输出 “程序继续执行&hellip;”</p>
<h5 id="622-try-with-resources">6.2.2 try-with-resources<a hidden class="anchor" aria-hidden="true" href="#622-try-with-resources">#</a></h5>
<blockquote>
<p>Java中，对于文件操作IO流、数据库连接等开销非常昂贵的资源，用完之后必须及时通过close方法将&gt;其关闭，否则资源会一直处于打开状态，可能会导致内存泄露等问题。 关闭资源的常用方式就是在finally块里调用close方法将资源关闭</p>
</blockquote>
<p>所以对于流的操作我们经常回用到如下代码</p>
<p>java</p>
<p>代码解读</p>
<p>复制代码</p>
<p><code>//读取文本文件的内容 import java.io.File; import java.io.FileNotFoundException; import java.util.Scanner; public class TestException {     public static void main(String[] args) {         Scanner scanner = null;         try {             scanner = new Scanner(new File(&quot;D://xiezhr.txt&quot;));             while (scanner.hasNext()) {                 System.out.println(scanner.nextLine());             }         } catch (FileNotFoundException e) {             e.printStackTrace();         } finally {             if (scanner != null) {                 scanner.close();             }         }     } } //输出 个人博客：www.xiezhrspace.cn 个人公众号：XiezhrSpace 欢迎你关注</code></p>
<p><strong>分析：</strong> 上述代码中我们通过io流读取D盘xiezhr.txt文件中的内容，并将其内容按行打印出来。最后在<code>finally</code>代码块中将scanner关闭</p>
<p>Java 7 之后，新的语法糖 try-with-resources 可以简写上述代码</p>
<p>java</p>
<p>代码解读</p>
<p>复制代码</p>
<p><code>import java.io.File; import java.io.FileNotFoundException; import java.util.Scanner; public class TestException {     public static void main(String[] args) {         try(Scanner scanner = new Scanner(new File(&quot;D://xiezhr.txt&quot;))){             while (scanner.hasNext()) {                 System.out.println(scanner.nextLine());             }         }catch (FileNotFoundException e){             e.printStackTrace();         }     } } //输出 个人博客：www.xiezhrspace.cn 个人公众号：XiezhrSpace 欢迎你关注</code></p>
<p>两段代码实现的功能是一样的，但明显try-with-resources 写法简单了好多。我们也更提倡<strong>优先使用 try-with-resources 而不是try-finally</strong>。</p>
<h5 id="623-抛出异常">6.2.3 抛出异常<a hidden class="anchor" aria-hidden="true" href="#623-抛出异常">#</a></h5>
<blockquote>
<p>当一个方法产生某种异常，但是不确定如何处理这种异常，那么就需要在该方法的头部显示地申明抛出异常，表明该方法将不对这些异常进行处理，而用该方法<strong>调用者负责处理</strong></p>
</blockquote>
<h6 id="6231-thorows">6.2.3.1 thorows<a hidden class="anchor" aria-hidden="true" href="#6231-thorows">#</a></h6>
<p>①语法格式 <code>returnType method_name(paramList) throws Exception 1,Exception2,…{…}</code></p>
<ul>
<li><code>returnType</code> 表示返回值类型</li>
<li><code>method_name</code> 表示方法名</li>
<li><code>paramList</code> 表示参数列表；</li>
<li><code>Exception 1，Exception2，…</code> 表示异常类 如果有多个异常类，它们之间用逗号分隔。这些异常类可以是方法中调用了可能拋出异常的方法而产生的异常，也可以是方法体中生成并拋出的异常</li>
</ul>
<p>②使用场景 当前方法不知道如何处理这种类型的异常，该异常应该由向上一级的调用者处理； 如果 main 方法也不知道如何处理这种类型的异常，也可以使用 throws 声明抛出异常，该异常将交给 JVM 处理。 JVM 对异常的处理方法是，打印异常的跟踪栈信息，并中止程序运行，这就是前面程序在遇到异常后自动结束的原因</p>
<p>③实践操作</p>
<p>java</p>
<p>代码解读</p>
<p>复制代码</p>
<p><code>import java.io.File; import java.io.IOException; import java.util.Scanner; public class TestException {     //定义方法时声明抛出异常，方法中出现的异常自己不处理，交由调用者处理     public void readfile() throws IOException {         // 读取文件         Scanner scanner = new Scanner(new File(&quot;D://xiezhr.txt&quot;));         while (scanner.hasNext()) {             System.out.println(scanner.nextLine());         }         scanner.close();     }     public static void main(String[] args)  {         TestException tt = new TestException();         try {             //调用readfile方法             tt.readfile();         } catch (IOException e) {             //打印异常             e.printStackTrace();         }     } } //输出 个人博客：www.xiezhrspace.cn 个人公众号：XiezhrSpace 欢迎你关注</code></p>
<p><strong>分析：</strong> 以上代码，首先在定义 readFile() 方法时用 <code>throws</code> 关键字声明在该方法中可能产生的异常，然后在 <code>main()</code> 方法中调用<code>readFile()</code> 方法，并使用 <code>catch</code> 语句捕获产生的异常</p>
<p>④ 异常处理流程图 <img loading="lazy" src="https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/ee08c7716c984522918550936017090f~tplv-k3u1fbpfcp-zoom-in-crop-mark:1512:0:0:0.awebp" alt="在这里插入图片描述"  />
</p>
<p>注意：子类方法声明抛出的异常类型应该是父类方法声明抛出的异常类型的子类或相同，子类方法声明抛出的异常不允许比父类方法声明抛出的异常多。</p>
<p>//下面程序编译就报错，原因时子类抛出比父类还大的异常</p>
<p>java</p>
<p>代码解读</p>
<p>复制代码</p>
<p><code>public class OverrideThrows {         public void test() throws IOException {             FileInputStream fis = new FileInputStream(&quot;a.txt&quot;);         }     }   class Sub extends OverrideThrows {       // 子类方法声明抛出了比父类方法更大的异常       public void test() throws Exception {       }   }</code></p>
<h6 id="6231-throw">6.2.3.1 throw<a hidden class="anchor" aria-hidden="true" href="#6231-throw">#</a></h6>
<blockquote>
<p>throw用来直接抛出一个异常</p>
</blockquote>
<p>①语法 <code>throw ExceptionObject;</code></p>
<ul>
<li>ExceptionObject 必须是 Throwable 类或其子类的对象</li>
<li>如果是自定义异常类，也必须是 Throwable 的直接或间接子类</li>
</ul>
<p>②执行原理 throw 语句执行时，它后面的语句将不执行； 此时程序转向调用者程序，寻找与之相匹配的 catch 语句，执行相应的异常处理程序。 如果没有找到相匹配的 catch 语句，则再转向上一层的调用程序。这样逐层向上，直到最外层的异常处理程序终止程序并打印出调用栈情况</p>
<p>③实践操作</p>
<p>java</p>
<p>代码解读</p>
<p>复制代码</p>
<p><code>import java.util.Scanner; public class TestException {     public boolean validateUserName(String username) {         boolean con = false;         if (username.length() &gt;4) {             // 判断用户名长度是否大于8位             if (&quot;admin&quot;.equals(username)) {                 con = true;             }else{                 throw new IllegalArgumentException(&quot;你输入的用户名不对&quot;);             }         } else {             throw new IllegalArgumentException(&quot;用户名长度必须大于 4 位！&quot;);         }         return con;     }     public static void main(String[] args) {         TestException te = new TestException();         Scanner input = new Scanner(System.in);         System.out.println(&quot;请输入用户名：&quot;);         String username = input.next();         try {             boolean con = te.validateUserName(username);             if (con) {                 System.out.println(&quot;用户名输入正确！&quot;);             }         } catch (IllegalArgumentException e) {             System.out.println(e);         }     } } //输出 ① 请输入用户名： abc java.lang.IllegalArgumentException: 用户名长度必须大于 4 位！ ② 请输入用户名： abcdef java.lang.IllegalArgumentException: 你输入的用户名不对 ③ 请输入用户名： admin 用户名输入正确！</code></p>
<h5 id="624-自定义异常">6.2.4 自定义异常<a hidden class="anchor" aria-hidden="true" href="#624-自定义异常">#</a></h5>
<blockquote>
<p>当Java提供的内置异常类型不能满足我们的需求时，我们可以设计自己的异常类型。</p>
</blockquote>
<p>①语法格式 <code>class XXXException extends Exception|RuntimeException</code></p>
<ul>
<li>一般将自定义异常类的类名命名为 XXXException，其中 XXX 用来代表该异常的作用</li>
<li>自定义异常类需要继承 Exception 类或其子类，如果自定义运行时异常类需继承 RuntimeException 类或其子类</li>
<li>自定义异常类一般包含两个构造方法：一个是无参的默认构造方法，另一个构造方法以字符串的形式接收一个定制的异常消息，并将该消息传递给超类的构造方法。</li>
</ul>
<p>②实践操作</p>
<p>java</p>
<p>代码解读</p>
<p>复制代码</p>
<p><code>import java.util.Scanner; public class TestException {     public static void main(String[] args) {        int age;        Scanner scanner = new Scanner(System.in);         System.out.println(&quot;请输入你的年龄&quot;);         age=scanner.nextInt();         try {             if(age &lt; 0) {                 throw new AgeException(&quot;您输入的年龄为负数！输入有误！&quot;);             } else if(age &gt; 100) {                 throw new AgeException(&quot;您输入的年龄大于100！输入有误！&quot;);             } else {                 System.out.println(&quot;您的年龄为：&quot;+age);             }         } catch (AgeException e) {             e.printStackTrace();         }     } } //输出 ① 请输入你的年龄 120 com.xiezhr.AgeException: 您输入的年龄大于100！输入有误！ 	at com.xiezhr.TestException.main(TestException.java:15) ② 请输入你的年龄 -34 com.xiezhr.AgeException: 您输入的年龄为负数！输入有误！ 	at com.xiezhr.TestException.main(TestException.java:13) ③ 请输入你的年龄 30 您的年龄为：30</code></p>
<h4 id="625-多异常捕获">6.2.5 多异常捕获<a hidden class="anchor" aria-hidden="true" href="#625-多异常捕获">#</a></h4>
<blockquote>
<p>Java7以后，catch 语句可以有多个，用来匹配多个异常</p>
</blockquote>
<p>①语法格式</p>
<p>java</p>
<p>代码解读</p>
<p>复制代码</p>
<p><code>try{     // 可能会发生异常的语句 } catch (IOException | ParseException e) {     // 异常处理 }</code></p>
<ul>
<li>多种异常类型之间用竖线|隔开</li>
<li>异常变量有隐式的 final 修饰，因此程序不能对异常变量重新赋值</li>
</ul>
<p>② 异常书写方式变化</p>
<p>java</p>
<p>代码解读</p>
<p>复制代码</p>
<p><code>try{     // 可能会发生异常的语句 } catch (FileNotFoundException e) {     // 调用方法methodA处理 } catch (IOException e) {     // 调用方法methodA处理 } catch (ParseException e) {     // 调用方法methodA处理 }</code></p>
<p>变成</p>
<p>java</p>
<p>代码解读</p>
<p>复制代码</p>
<p><code>try{     // 可能会发生异常的语句 } catch (FileNotFoundException | IOException | ParseException e) {     // 调用方法处理 }</code></p>
<p>③实践操作</p>
<p>java</p>
<p>代码解读</p>
<p>复制代码</p>
<p><code>import java.util.Scanner; public class TestException {     public static void main(String[] args) {        int num1;        int num2;         try {             Scanner scanner = new Scanner(System.in);             System.out.println(&quot;请输入num1的值&quot;);             num1=scanner.nextInt();             System.out.println(&quot;请输入num2的值&quot;);             num2=scanner.nextInt();             int num= num1/num2;             System.out.println(&quot;你输入的两个数相除，结果是&quot; + num);         } catch (IndexOutOfBoundsException | NumberFormatException | ArithmeticException e){             System.out.println(&quot;程序发生了数组越界、数字格式异常、算术异常之一&quot;);             e.printStackTrace();         }         catch (Exception e) {             System.out.println(&quot;未知异常&quot;);             e.printStackTrace();         }     } } //输出 ① 请输入num1的值 12 请输入num2的值 0 程序发生了数组越界、数字格式异常、算术异常之一 java.lang.ArithmeticException: / by zero 	at com.xiezhr.TestException.main(TestException.java:15) ② 请输入num1的值 6888888888 未知异常 java.util.InputMismatchException: For input string: &quot;6888888888&quot; 	at java.util.Scanner.nextInt(Scanner.java:2123) 	at java.util.Scanner.nextInt(Scanner.java:2076) 	at com.xiezhr.TestException.main(TestException.java:12) ③ 请输入num1的值 12 请输入num2的值 4 你输入的两个数相除，结果是3</code></p>
<p><strong>分析：</strong> 上面程序中<code>IndexOutOfBoundsException|NumberFormatException|ArithmeticException</code>来定义异常类型，这就表明该 <code>catch 块</code>可以同时捕获这 3 种类型的异常</p>
<h3 id="七throwable-类常用方法">七、Throwable 类常用方法<a hidden class="anchor" aria-hidden="true" href="#七throwable-类常用方法">#</a></h3>
<ul>
<li><code>String getMessage()</code>: 返回异常发生时的简要描述</li>
<li><code>String toString()</code>: 返回异常发生时的详细信息</li>
<li><code>String getLocalizedMessage()</code>: 返回异常对象的本地化信息。使用 Throwable 的子类覆盖这个方法，可以生成本地化信息。如果子类没有覆盖该方法，则该方法返回的信息与 getMessage()返回的结果相同</li>
<li><code>void printStackTrace()</code>: 在控制台上打印 <code>Throwable</code> 对象封装的异常信息</li>
</ul>
<h3 id="八易混概念">八、易混概念<a hidden class="anchor" aria-hidden="true" href="#八易混概念">#</a></h3>
<h4 id="81-error和exception的异同">8.1 Error和Exception的异同<a hidden class="anchor" aria-hidden="true" href="#81-error和exception的异同">#</a></h4>
<ul>
<li><code>Error</code> 和<code>Exception</code> 都有共同的祖先<code>Throwable</code>，即<code>Error</code> 和<code>Exception</code> 都是<code>Throwable</code>的子类</li>
<li><code>Exception</code> :程序本身可以处理的异常，可以通过 <code>try-catch</code> 来进行捕获。<code>Exception</code>又可以分为 <code>Checked Exception</code> (受检查异常，必须处理) 和 <code>Unchecked Exception</code>(不受检查异常，可以不处理)。</li>
<li><code>Error</code> ：<code>Error</code> 属于程序无法处理的错误 ，我们没办法通过 <code>try-catch</code> 来进行捕获 。例如 Java 虚拟机运行错误（<code>Virtual MachineError</code>）、虚拟机内存不够错误(<code>OutOfMemoryError</code>)、类定义错误（<code>NoClassDefFoundError</code>）等 。这些异常发生时，Java 虚拟机（JVM）一般会选择线程终止</li>
</ul>
<h4 id="82-throw和throws的区别">8.2 throw和throws的区别<a hidden class="anchor" aria-hidden="true" href="#82-throw和throws的区别">#</a></h4>
<ul>
<li><code>throws</code> 用来声明一个方法可能抛出的所有异常信息，表示出现异常的一种可能性，但并不一定会发生这些异常；<code>throw</code> 则是指拋出的一个具体的异常类型，执行 <code>throw</code> 则一定抛出了某种异常对象。</li>
<li>通常在一个方法（类）的声明处通过 <code>throws</code> 声明方法（类）可能拋出的异常信息，而在方法（类）内部通过 <code>throw</code>声明一个具体的异常信息。</li>
<li><code>throws</code> 通常不用显示地捕获异常，可由系统自动将所有捕获的异常信息抛给上级方法； <code>throw</code> 则需要用户自己捕获相关的异常，而后再对其进行相关包装，最后将包装后的异常信息抛出</li>
</ul>
<h4 id="83-checked-exception-和-unchecked-exception">8.3 Checked Exception 和 Unchecked Exception<a hidden class="anchor" aria-hidden="true" href="#83-checked-exception-和-unchecked-exception">#</a></h4>
<ul>
<li><code>Checked Exception</code> 受检查异常 Java 代码在编译过程中，如果受检查异常没有被 catch或者throws 关键字处理的话，就没办法通过编译</li>
<li>常见的受检查异常有： IO 相关的异常、<code>ClassNotFoundException</code> 、<code>SQLException</code></li>
<li>例如，下面就是 -<img loading="lazy" src="https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/46b33d279b53402485a1ff086628cc56~tplv-k3u1fbpfcp-zoom-in-crop-mark:1512:0:0:0.awebp" alt="在这里插入图片描述"  />
</li>
<li><code>Unchecked Exception</code> 即 不受检查异常 ，Java 代码在编译过程中 ，我们即使不处理不受检查异常也可以正常通过编译。</li>
<li>我们经常看到的有以下几种 <code>NullPointerException</code> ：空指针错误 <code>IllegalArgumentException</code> ：参数错误比如方法入参类型错误 <code>NumberFormatException</code>：字符串转换为数字格式错误 <code>ArrayIndexOutOfBoundsException</code>：数组越界错误 <code>ClassCastException</code>：类型转换错误 <code>ArithmeticException</code>：算术错误 <code>SecurityException</code> ：安全错误比如权限不够 <code>UnsupportedOperationException</code>：不支持的操作错误比如重复创建同一用户</li>
</ul>
<h4 id="84-try-with-resources-与-try-catch-finally">8.4 try-with-resources 与 try-catch-finally<a hidden class="anchor" aria-hidden="true" href="#84-try-with-resources-与-try-catch-finally">#</a></h4>
<ul>
<li><code>try-with-resources</code> 是Java 1.7增加的新语法糖，在<code>try</code> 代码块结束之前会自动关闭资源。</li>
<li><code>try-with-resources</code> 适用于任何实现 <code>java.lang.AutoCloseable</code>或者 <code>java.io.Closeable</code> 的对象, 字节输入流（<code>InputStream</code>），字节输出流（<code>OutputStream</code>），字符输入流（<code>Reader</code>），字符输出流（<code>Writer</code>）均实现了这接口</li>
<li><code>try-catch-finally</code> 没有限制条件，<code>finally</code>不仅可以关闭资源，还可以用于执行其他代码块；</li>
<li><code>try-with-resources</code> 代码更加简洁，有限制条件，资源会立即被关闭</li>
<li><code>finally</code>关闭资源不会立即关闭，取决与网络和系统，可能会很快，也可能会等一两天，所以，最好不要使用finally作为业务流程的控制，在《Effective java》一书 的第9条：try-with-resources优先于try-finally 中有相关详细的介绍，其中提到了许多由于finally延迟导致的网络事件</li>
</ul>
<h3 id="九springboot-中优雅的处理统一异常返回">九、SpringBoot 中优雅的处理统一异常返回<a hidden class="anchor" aria-hidden="true" href="#九springboot-中优雅的处理统一异常返回">#</a></h3>
<blockquote>
<p>日常开发中，我们处理异常一般都会用到<code>try-catch</code> 、<code>throw</code>和<code>throws</code> 的方式抛出异常。 这种方式不经程序员处理麻烦，对用户来说也不太友好 我们都希望不用写过多的重复代码处理异常，又能提升用户体验。这时候<strong>全局异常处理</strong>就显得很便捷很重要了</p>
</blockquote>
<h4 id="91-全局异常捕获与处理">9.1 全局异常捕获与处理<a hidden class="anchor" aria-hidden="true" href="#91-全局异常捕获与处理">#</a></h4>
<blockquote>
<p> Springboot对提供了一个 <code>@ControllerAdvice</code>注解以及 <code>@ExceptionHandler</code>注解，分别用于开启全局的异常捕获和说明捕获哪些异常，对那些异常进行处理。</p>
</blockquote>
<p>java</p>
<p>代码解读</p>
<p>复制代码</p>
<p><code>@ControllerAdvice public class MyExceptionHandler {     @ExceptionHandler(value =Exception.class) 	public String exceptionHandler(Exception e){ 		System.out.println(&quot;出现了一个异常&quot;+e);        	return e.getMessage();     } }</code></p>
<p><strong>分析</strong> 上面这段代码就是说，只要是代码运行过程中有异常就会进行捕获，并输出出这个异常。然后我们随便编写一个会发生异常的代码，测试出来的异常是这样的。</p>
<p><img loading="lazy" src="https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/3d83786d653b4633a888a161a9bb1680~tplv-k3u1fbpfcp-zoom-in-crop-mark:1512:0:0:0.awebp" alt="在这里插入图片描述"  />
 这对于前后端分离来说这样的报错对用户并不好，前后端分离之后唯一的交互就是json了，我们也希望将后端的异常变成json返回给前端处理。</p>
<h4 id="92-用枚举类型记录已知错误信息与成功信息">9.2 用枚举类型记录已知错误信息与成功信息<a hidden class="anchor" aria-hidden="true" href="#92-用枚举类型记录已知错误信息与成功信息">#</a></h4>
<blockquote>
<p><code>ErrorEnum</code>枚举类中定义了常见的错误码以及错误的提示信息。 <code>SuccEnum</code> 枚举类中定义了成功码及成功提示信息</p>
</blockquote>
<p>至于这里为什么用枚举就不具体说了，网上文章说说的也比较多了 具体可以参照：<a href="https://link.juejin.cn?target=https%3A%2F%2Fblog.csdn.net%2Fqq_27093465%2Farticle%2Fdetails%2F52180865" title="https://blog.csdn.net/qq_27093465/article/details/52180865">Java 枚举(enum) 详解7种常见的用法</a></p>
<p>① 已知错误信息</p>
<p>java</p>
<p>代码解读</p>
<p>复制代码</p>
<p><code>public enum ErrorEnum {     // 数据操作错误定义     NO_PERMISSION(403,&quot;没有权限访问&quot;),     NO_AUTH(401,&quot;请先登录系统&quot;),     NOT_FOUND(404, &quot;未找到该资源!&quot;),     USER_NOT_FIND(402, &quot;未找到用户信息&quot;),     INTERNAL_SERVER_ERROR(500, &quot;服务器出问题了&quot;),     UNKNOW_ERR(-1,&quot;未知错误&quot;)     ;     /** 错误码 */     private Integer errorCode;     /** 错误信息 */     private String errorMsg;     ErrorEnum(Integer errorCode, String errorMsg) {         this.errorCode = errorCode;         this.errorMsg = errorMsg;     }     public Integer getErrorCode() {         return errorCode;     }     public String getErrorMsg() {         return errorMsg;     } }</code></p>
<p>② 成功信息</p>
<p>java</p>
<p>代码解读</p>
<p>复制代码</p>
<p><code>public enum SuccEnum  {     SUCCESS(200, &quot;success&quot;);     /** 成功码 **/     private Integer succCode;     /* 成功信息*/     private String succMsg;     SuccEnum(Integer succCode, String succMsg) {         this.succCode = succCode;         this.succMsg = succMsg;     }     public Integer getSuccCode() {         return succCode;     }     public String getSuccMsg() {         return succMsg;     } }</code></p>
<h4 id="93-定义统一结果返回与异常返回">9.3 定义统一结果返回与异常返回<a hidden class="anchor" aria-hidden="true" href="#93-定义统一结果返回与异常返回">#</a></h4>
<ul>
<li><code>success</code>：用<code>boolean</code> 类型标识，标识是否成功</li>
<li><code>code</code>: 状态码，区分各种报错信息与成功返回</li>
<li><code>msg</code> : 成功或错误提示信息</li>
<li><code>data</code> : 返回的数据</li>
</ul>
<p>java</p>
<p>代码解读</p>
<p>复制代码</p>
<p><code>@Data public class Result&lt;T&gt; {     //是否成功     private Boolean success;     //状态码     private Integer code;     //提示信息     private String msg;     //数据     private T data;     public Result() {     }     //自定义返回结果的构造方法     public  Result(Boolean success,Integer code, String msg,T data) {         this.success = success;         this.code = code;         this.msg = msg;         this.data = data;     } }</code></p>
<h4 id="94-封装工具类返回结果">9.4 封装工具类返回结果<a hidden class="anchor" aria-hidden="true" href="#94-封装工具类返回结果">#</a></h4>
<blockquote>
<p>这里我们定义好了统一的结果返回，其中里面的静态方法是用来当程序异常的时候转换成异常返回规定的格式。</p>
</blockquote>
<p>java</p>
<p>代码解读</p>
<p>复制代码</p>
<p><code>public class ResultUtil {     //成功，并返回具体数据     public static Result success(SuccEnum succEnum,Object obj){         Result result = new Result();         result.setSuccess(true);         result.setMsg(succEnum.getSuccMsg());         result.setCode(succEnum.getSuccCode());         result.setData(obj);         return result;     }     //成功，无数据返回     public static Result succes(SuccEnum succEnum){         Result result = new Result();         result.setSuccess(true);         result.setMsg(succEnum.getSuccMsg());         result.setCode(succEnum.getSuccCode());         result.setData(null);         return result;     }     //自定义异常返回的结果     public static Result defineError(DefinitionException de){         Result result = new Result();         result.setSuccess(false);         result.setCode(de.getErrorCode());         result.setMsg(de.getErrorMsg());         result.setData(null);         return result;     }     //其他异常处理方法返回的结果     public static Result otherError(ErrorEnum errorEnum){         Result result = new Result();         result.setSuccess(false);         result.setMsg(errorEnum.getErrorMsg());         result.setCode(errorEnum.getErrorCode());         result.setData(null);         return result;     } }</code></p>
<h4 id="95-自定义异常">9.5 自定义异常<a hidden class="anchor" aria-hidden="true" href="#95-自定义异常">#</a></h4>
<blockquote>
<p>内置异常不能满足我们业务需求的时候，我们就需要自定义异常</p>
</blockquote>
<p>java</p>
<p>代码解读</p>
<p>复制代码</p>
<p><code>public class DefinitionException extends RuntimeException {     protected Integer errorCode;     protected String errorMsg;     public DefinitionException(){     }     public DefinitionException(Integer errorCode, String errorMsg) {         this.errorCode = errorCode;         this.errorMsg = errorMsg;     }     public Integer getErrorCode() {         return errorCode;     }     public void setErrorCode(Integer errorCode) {         this.errorCode = errorCode;     }     public String getErrorMsg() {         return errorMsg;     }     public void setErrorMsg(String errorMsg) {         this.errorMsg = errorMsg;     } }</code></p>
<h4 id="96-定义全局异常处理类">9.6 定义全局异常处理类<a hidden class="anchor" aria-hidden="true" href="#96-定义全局异常处理类">#</a></h4>
<blockquote>
<p>我们自定义一个全局异常处理类，来处理各种异常,包括<strong>自己定义的异常</strong>和<strong>内部异常</strong>。这样可以简化不少代码，不用自己对每个异常都使用try，catch的方式来实现</p>
</blockquote>
<p>java</p>
<p>代码解读</p>
<p>复制代码</p>
<p><code>@ControllerAdvice public class GlobalExceptionHandler {     /**      * 处理自定义异常      *      */     @ExceptionHandler(value = DefinitionException.class)     @ResponseBody     public Result bizExceptionHandler(DefinitionException e) {         return ResultUtil.defineError(e);     }     /**      * 处理其他异常      *      */     @ExceptionHandler(value = Exception.class)     @ResponseBody     public Result exceptionHandler( Exception e) {         return ResultUtil.otherError(ErrorEnum.UNKNOW_ERR);     } }</code></p>
<p><strong>说明：</strong> 方法上面加上一个 <code>@ResponseBody</code>的注解，用于将对象解析成json,方便前后端的交互，也可以使用 <code>@ResponseBody</code>放在异常类上面</p>
<h4 id="97-代码测试">9.7 代码测试<a hidden class="anchor" aria-hidden="true" href="#97-代码测试">#</a></h4>
<h5 id="971-定义user实体类">9.7.1 定义User实体类<a hidden class="anchor" aria-hidden="true" href="#971-定义user实体类">#</a></h5>
<p>java</p>
<p>代码解读</p>
<p>复制代码</p>
<p><code>@Data public class User {     //唯一标识id     private Integer id;     //姓名     private String name;     //性别     private String sex;     //年龄     private Integer age; }</code></p>
<h5 id="972-定义controller类">9.7.2 定义controller类<a hidden class="anchor" aria-hidden="true" href="#972-定义controller类">#</a></h5>
<p>java</p>
<p>代码解读</p>
<p>复制代码</p>
<p><code>@RestController @RequestMapping(&quot;/result&quot;) public class ExceptionController {     @Autowired     private GlobalExceptionHandler globalExceptionHandler;     @GetMapping(&quot;/getUser&quot;)     public Result getStudent(){         User user = new User();         user.setId(100);         user.setName(&quot;xiezhr&quot;);         user.setAge(21);         user.setSex(&quot;男&quot;);         Result result = ResultUtil.success(SuccEnum.SUCCESS, user);         return result;     }     @GetMapping(&quot;/getDefException&quot;)     public Result DeException(){         throw new DefinitionException(400,&quot;我出错了&quot;);     }     @GetMapping(&quot;/getException&quot;)     public Result Exception(@RequestParam(&quot;name&quot;) String name, @RequestParam(&quot;pwd&quot;) String pwd){         Result result = ResultUtil.success(SuccEnum.SUCCESS);         try {             if (&quot;admin&quot;.equals(name)){                 User user = new User();                 user.setId(101);                 user.setName(&quot;xiezhr&quot;);                 user.setAge(18);                 user.setSex(&quot;男&quot;);                 result =  ResultUtil.success(SuccEnum.SUCCESS,user);             }else if (name.equals(&quot;xiezhr&quot;)){                 result =  ResultUtil.otherError(ErrorEnum.USER_NOT_FIND);             }else{                 int i = 1/0;             }         }catch (Exception e){             result =  globalExceptionHandler.exceptionHandler(e);         }         return result;     } }</code></p>
<h4 id="98-接口测试">9.8 接口测试<a hidden class="anchor" aria-hidden="true" href="#98-接口测试">#</a></h4>
<h5 id="981-获取没有异常的数据返回">9.8.1 获取没有异常的数据返回<a hidden class="anchor" aria-hidden="true" href="#981-获取没有异常的数据返回">#</a></h5>
<p><code>http://localhost:8090/result/getUser</code> <img loading="lazy" src="https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/d5f8d517f5084f0393f0cdcd7bc920e4~tplv-k3u1fbpfcp-zoom-in-crop-mark:1512:0:0:0.awebp" alt="在这里插入图片描述"  />
</p>
<h5 id="982-自定义异常返回">9.8.2 自定义异常返回<a hidden class="anchor" aria-hidden="true" href="#982-自定义异常返回">#</a></h5>
<p><code>http://localhost:8090/result/getDefException</code> <img loading="lazy" src="https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/4347d376ff38459b8585c82ef4c6a45f~tplv-k3u1fbpfcp-zoom-in-crop-mark:1512:0:0:0.awebp" alt="在这里插入图片描述"  />
 <code>http://localhost:8090/result/getException?name=xiezhr&amp;pwd=123</code> <img loading="lazy" src="https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/902056c877ea4ffab4a0d2c398da4c01~tplv-k3u1fbpfcp-zoom-in-crop-mark:1512:0:0:0.awebp" alt="在这里插入图片描述"  />
</p>
<h5 id="983-其他的异常-返回">9.8.3 其他的异常 返回<a hidden class="anchor" aria-hidden="true" href="#983-其他的异常-返回">#</a></h5>
<p><code>http://localhost:8090/result/getException?name=ff&amp;pwd=abc</code> <img loading="lazy" src="https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/8d9b179560504c3294d7d5c400d05394~tplv-k3u1fbpfcp-zoom-in-crop-mark:1512:0:0:0.awebp" alt="在这里插入图片描述"  />
</p>
<h3 id="十异常处理及规约">十、异常处理及规约<a hidden class="anchor" aria-hidden="true" href="#十异常处理及规约">#</a></h3>
<p>异常的处理⽅式有两种。 1、 ⾃⼰处理。 2、 向上抛， 交给调⽤者处理。</p>
<p>异常， 千万不能捕获了之后什么也不做。 或者只是使⽤e.printStacktrace。</p>
<p>具体的处理⽅式的选择其实原则⽐较简明： ⾃⼰明确的知道如何处理的， 就要处理掉。 不知道如何处理的， 就交给调⽤者处理。</p>
<p>下面时<strong>阿里巴巴Java开发手册</strong>关于<strong>异常处理规则</strong></p>
<p><strong>①【强制】</strong> Java类库中定义的可以通过预检查方式规避的<code>RuntimeException</code>不应该通过<code>catch</code>的方式处理，如<code>NullPointerException</code>、<code>IndexOutOfBoundsException</code>等</p>
<blockquote>
<p>说明：无法通过预检查的异常不在此列，比如当解析字符串形式的数字时，可能存在数字格式错误，通过<code>catch NumberFormatException</code>实现</p>
</blockquote>
<p>正例：</p>
<p>java</p>
<p>代码解读</p>
<p>复制代码</p>
<p><code>if(obj!=null){....}</code></p>
<p>反例：</p>
<p>java</p>
<p>代码解读</p>
<p>复制代码</p>
<p><code>try{ 	obj.method(); }catch(NullPointerException e){ 	... }</code></p>
<p><strong>②【强制】</strong> 异常捕获后不要用来做流程控制和条件控制</p>
<blockquote>
<p>说明：异常设计的初衷是解决程序运行中各种意外，且异常的处理效率比条件判断方式要第很多。</p>
</blockquote>
<p><strong>③【强制】</strong> <code>catch</code> 时请分清稳定代码和非稳定代码。稳定代码一般指本机运行且执行结果确定性高的代码。对于非稳定代码的<code>catch</code> 尽可能在进行异常类型的分区后，再做对应的异常处理</p>
<blockquote>
<p>说明：对大段代码进行<code>try-catch</code>,将使程序无法根据不同的异常做出正确的“应激”反应，也不利于定位问题，这是一种不负责的表现</p>
</blockquote>
<p>正例：在用户注册场景中，如果用户输入非法字符串，或用户名称已存在，或用户输入的密码过于简单，那么程序会作出分门别类的判断并提示用户。</p>
<p><strong>④【强制】</strong> 捕获异常使为了处理异常，不要捕获了却说明都不处理而抛弃之，如果不想处理它，请将异常抛给它的调用者。最外层的业务使用者必须处理异常，将其转换为用户可以理解的内容。</p>
<p><strong>⑤【强制】</strong> 在事务场景中，抛出异常被<code>catch</code> 后，如果需要回滚，那么一定要注意手动回滚事务。</p>
<p><strong>⑥【强制】</strong> <code>finally</code> 块必须对资源对象、流对象进行关闭操作，如果有一次要做<code>try-catch</code>操作。</p>
<blockquote>
<p>说明：对于JDK7即以上版本，可以使用<code>try-catch-resource</code> 方式</p>
</blockquote>
<p><strong>⑦【强制】</strong> 不要在<code>finally</code>块中使用return</p>
<blockquote>
<p>说明<code>try</code> 块中<code>return</code> 语句执行成功后，并不马上返回，而是继续执行<code>finally</code> 块中的语句，如果此处存在<code>return</code>语句，则在此直接返回，无情地丢弃<code>try</code>块中的返回点。</p>
</blockquote>
<p>正例：</p>
<p>java</p>
<p>代码解读</p>
<p>复制代码</p>
<p><code>private int x =0; public int checkReturn(){ 	try{ 		//x=1,此处不返回 		return ++x; 	}finally{ 		//返回的结果是2 		return ++x; 	} }</code></p>
<p><strong>⑧【强制】</strong> 捕获异常与抛出异常必须完全匹配，或者捕获异常时抛出异常的父类。</p>
<blockquote>
<p>说明：如果以及对方抛出的时绣球，实际接收到的时铅球，就会产生意外</p>
</blockquote>
<p><strong>⑨【强制】</strong> 在调用RPC、二方包或动态生成类的相关方法时，捕获异常必须使用Throwable拦截。</p>
<blockquote>
<p>说明：通过反射机制调用方法，如果找不到方法，则抛出<code>NoSuchMethodException</code>。 在说明情况下抛出<code>NoSuchMethodException</code>呢？二方包在类冲突时，仲裁机制可能导致引入非预期的版本使类的方法签名不匹配，或者在字节码修改框架（比如：ASM）动态创建或修改类时，修改了相应的方法签名。对于这些情况，即使在代码编译期是正确的，在代码运行期也会抛出<code>NoSuchMethodException</code></p>
</blockquote>
<p><strong>⑩【推荐】</strong> 方法的返回值可以为<code>null</code>,不强制返回空集合或者空对象等，必须添加注释充分说明在说明情况下会返回<code>null</code>值。此时数据库<code>id</code>不支持存入负数二抛出异常。</p>
<blockquote>
<p>说明：本手册明确，防止产生NPE是调用者的责任。即使被调用方法返回空集合或者空对象，对调用者来说，也并非高枕无忧，必须考虑远程调用失败、序列化失败、运行时异常等场景返回<code>null</code>值的情况</p>
</blockquote>
<p><strong>⑪【推荐】</strong> 防止产生NPE时程序员的基本修养，注意NPE产生的场景。 1）当返回类型为基本数据类型，<code>return</code> 包装数据类型的对象时，自动拆箱有可能产生NPE 反例：</p>
<p>java</p>
<p>代码解读</p>
<p>复制代码</p>
<p><code>public int f(){ 	//如果为null,则自动拆箱，抛NPE。 	return Integer 对象; }</code></p>
<p>2）数据库的查询结果可能为<code>null</code> 3) 集合里的元素即使<code>isNotEmpty</code> , 取出的数据元素也有可能为<code>null</code></p>
<ol start="4">
<li>当远程调用返回对象时，一律要求进行空指针判断，以防止产生NPE。 5）对于<code>Session</code> 中获取的数据，建议进行NPE检查，以避免空指针 6）级联调用obj.getA().getB().getC();的一连串调用容易产生NPE。</li>
</ol>
<p><strong>⑫【推荐】</strong> 定义时区分 <code>unchecked/checked</code> 异常，避免直接抛出<code>new RuntimeException()</code>,更不允许抛出<code>Exception</code> 或者<code>Throwable</code>，应该使用业务含义的自定义异常。推荐业界已定义过的自定义异常，如：<code>DAOException / ServiceException</code> 等</p>
<p><strong>⑬ 【参考】</strong> 对于公司外的<code>HTTP/API</code> 开放接口，必须使用<code>“errorCode”</code>:应用内部推荐异常抛出； 跨应用间RPC调用优先考虑使用<code>Result</code> 方式，封装<code>isSuccess()</code> 方法、<code>errorCode</code> 和<code>errorMessage</code>。</p>
<blockquote>
<p>说明：关于RPC方法返回方式使用Result方式的理由 1）使用抛出异常返回方式，调用方式如果没有捕获到，就会产生运行时错误 2）如果不加栈信息，知识<code>new</code>自定义异常，加入自己理解的<code>errorMesage</code>，对于调用解决问题的帮助不会太多。如果加了栈信息，在频繁调用出错的情况下，数据序列化和传输的性能损耗也是问题。</p>
</blockquote>
<p><strong>⑭【参考】</strong> 避免出现重复的代码（<code>Don't Repeat Yourself</code>）,即DRY原则</p>
<blockquote>
<p>说明： 随意复制和粘贴代码，必然导致代码的重复，当以后需要修改时，需要修改所有的副本，容易遗漏。必要时抽取共性方法或公共类，甚至将代码组件化。</p>
</blockquote>
<p>正例： 一个类中由多个<code>public</code> 方法，都需要进行数行相同的参数校验操作，这个时候请抽取：</p>
<p>java</p>
<p>代码解读</p>
<p>复制代码</p>
<p><code>private boolean checkParam(DTO dto){...}</code></p>
<p>本期内容到这就结束了，各位小伙伴们，我们下期见 (●&rsquo;◡&rsquo;●)</p>


  </div>

  <footer class="post-footer">
    <ul class="post-tags">
      <li><a href="http://localhost:1313/tags/java/">Java</a></li>
      <li><a href="http://localhost:1313/tags/%E5%90%8E%E7%AB%AF/">后端</a></li>
    </ul>
<nav class="paginav">
  <a class="prev" href="http://localhost:1313/posts/juejin/%E6%88%96%E8%AE%B8%E4%BD%A0%E6%83%B3%E8%A6%81%E7%9A%84%E7%94%BB%E5%9B%BE%E5%B7%A5%E5%85%B7%E5%9C%A8%E8%BF%99%E9%87%8C/">
    <span class="title">« 上一页</span>
    <br>
    <span>或许你想要的画图工具在这里</span>
  </a>
  <a class="next" href="http://localhost:1313/posts/juejin/%E6%9C%89%E6%84%8F%E6%80%9D%E5%9C%A3%E8%AF%9E%E8%8A%82%E8%87%AA%E5%B7%B1%E5%81%9A%E4%B8%80%E4%B8%AA%E8%A3%85%E9%A5%B0%E5%9C%A3%E8%AF%9E%E5%B8%BD%E5%A4%B4%E5%83%8F%E7%9A%84app/">
    <span class="title">下一页 »</span>
    <br>
    <span>有意思，圣诞节自己做一个装饰圣诞帽头像的APP！</span>
  </a>
</nav>


<ul class="share-buttons">
    <li>
        <a target="_blank" rel="noopener noreferrer" aria-label="share 啪，还敢抛出异常 on x"
            href="https://x.com/intent/tweet/?text=%e5%95%aa%ef%bc%8c%e8%bf%98%e6%95%a2%e6%8a%9b%e5%87%ba%e5%bc%82%e5%b8%b8&amp;url=http%3a%2f%2flocalhost%3a1313%2fposts%2fjuejin%2f%25E5%2595%25AA%25E8%25BF%2598%25E6%2595%25A2%25E6%258A%259B%25E5%2587%25BA%25E5%25BC%2582%25E5%25B8%25B8%2f&amp;hashtags=Java%2c%e5%90%8e%e7%ab%af">
            <svg version="1.1" viewBox="0 0 512 512" xml:space="preserve" height="30px" width="30px" fill="currentColor">
                <path
                    d="M512 62.554 L 512 449.446 C 512 483.97 483.97 512 449.446 512 L 62.554 512 C 28.03 512 0 483.97 0 449.446 L 0 62.554 C 0 28.03 28.029 0 62.554 0 L 449.446 0 C 483.971 0 512 28.03 512 62.554 Z M 269.951 190.75 L 182.567 75.216 L 56 75.216 L 207.216 272.95 L 63.9 436.783 L 125.266 436.783 L 235.9 310.383 L 332.567 436.783 L 456 436.783 L 298.367 228.367 L 432.367 75.216 L 371.033 75.216 Z M 127.633 110 L 164.101 110 L 383.481 400.065 L 349.5 400.065 Z" />
            </svg>
        </a>
    </li>
    <li>
        <a target="_blank" rel="noopener noreferrer" aria-label="share 啪，还敢抛出异常 on linkedin"
            href="https://www.linkedin.com/shareArticle?mini=true&amp;url=http%3a%2f%2flocalhost%3a1313%2fposts%2fjuejin%2f%25E5%2595%25AA%25E8%25BF%2598%25E6%2595%25A2%25E6%258A%259B%25E5%2587%25BA%25E5%25BC%2582%25E5%25B8%25B8%2f&amp;title=%e5%95%aa%ef%bc%8c%e8%bf%98%e6%95%a2%e6%8a%9b%e5%87%ba%e5%bc%82%e5%b8%b8&amp;summary=%e5%95%aa%ef%bc%8c%e8%bf%98%e6%95%a2%e6%8a%9b%e5%87%ba%e5%bc%82%e5%b8%b8&amp;source=http%3a%2f%2flocalhost%3a1313%2fposts%2fjuejin%2f%25E5%2595%25AA%25E8%25BF%2598%25E6%2595%25A2%25E6%258A%259B%25E5%2587%25BA%25E5%25BC%2582%25E5%25B8%25B8%2f">
            <svg version="1.1" viewBox="0 0 512 512" xml:space="preserve" height="30px" width="30px" fill="currentColor">
                <path
                    d="M449.446,0c34.525,0 62.554,28.03 62.554,62.554l0,386.892c0,34.524 -28.03,62.554 -62.554,62.554l-386.892,0c-34.524,0 -62.554,-28.03 -62.554,-62.554l0,-386.892c0,-34.524 28.029,-62.554 62.554,-62.554l386.892,0Zm-288.985,423.278l0,-225.717l-75.04,0l0,225.717l75.04,0Zm270.539,0l0,-129.439c0,-69.333 -37.018,-101.586 -86.381,-101.586c-39.804,0 -57.634,21.891 -67.617,37.266l0,-31.958l-75.021,0c0.995,21.181 0,225.717 0,225.717l75.02,0l0,-126.056c0,-6.748 0.486,-13.492 2.474,-18.315c5.414,-13.475 17.767,-27.434 38.494,-27.434c27.135,0 38.007,20.707 38.007,51.037l0,120.768l75.024,0Zm-307.552,-334.556c-25.674,0 -42.448,16.879 -42.448,39.002c0,21.658 16.264,39.002 41.455,39.002l0.484,0c26.165,0 42.452,-17.344 42.452,-39.002c-0.485,-22.092 -16.241,-38.954 -41.943,-39.002Z" />
            </svg>
        </a>
    </li>
    <li>
        <a target="_blank" rel="noopener noreferrer" aria-label="share 啪，还敢抛出异常 on reddit"
            href="https://reddit.com/submit?url=http%3a%2f%2flocalhost%3a1313%2fposts%2fjuejin%2f%25E5%2595%25AA%25E8%25BF%2598%25E6%2595%25A2%25E6%258A%259B%25E5%2587%25BA%25E5%25BC%2582%25E5%25B8%25B8%2f&title=%e5%95%aa%ef%bc%8c%e8%bf%98%e6%95%a2%e6%8a%9b%e5%87%ba%e5%bc%82%e5%b8%b8">
            <svg version="1.1" viewBox="0 0 512 512" xml:space="preserve" height="30px" width="30px" fill="currentColor">
                <path
                    d="M449.446,0c34.525,0 62.554,28.03 62.554,62.554l0,386.892c0,34.524 -28.03,62.554 -62.554,62.554l-386.892,0c-34.524,0 -62.554,-28.03 -62.554,-62.554l0,-386.892c0,-34.524 28.029,-62.554 62.554,-62.554l386.892,0Zm-3.446,265.638c0,-22.964 -18.616,-41.58 -41.58,-41.58c-11.211,0 -21.361,4.457 -28.841,11.666c-28.424,-20.508 -67.586,-33.757 -111.204,-35.278l18.941,-89.121l61.884,13.157c0.756,15.734 13.642,28.29 29.56,28.29c16.407,0 29.706,-13.299 29.706,-29.701c0,-16.403 -13.299,-29.702 -29.706,-29.702c-11.666,0 -21.657,6.792 -26.515,16.578l-69.105,-14.69c-1.922,-0.418 -3.939,-0.042 -5.585,1.036c-1.658,1.073 -2.811,2.761 -3.224,4.686l-21.152,99.438c-44.258,1.228 -84.046,14.494 -112.837,35.232c-7.468,-7.164 -17.589,-11.591 -28.757,-11.591c-22.965,0 -41.585,18.616 -41.585,41.58c0,16.896 10.095,31.41 24.568,37.918c-0.639,4.135 -0.99,8.328 -0.99,12.576c0,63.977 74.469,115.836 166.33,115.836c91.861,0 166.334,-51.859 166.334,-115.836c0,-4.218 -0.347,-8.387 -0.977,-12.493c14.564,-6.47 24.735,-21.034 24.735,-38.001Zm-119.474,108.193c-20.27,20.241 -59.115,21.816 -70.534,21.816c-11.428,0 -50.277,-1.575 -70.522,-21.82c-3.007,-3.008 -3.007,-7.882 0,-10.889c3.003,-2.999 7.882,-3.003 10.885,0c12.777,12.781 40.11,17.317 59.637,17.317c19.522,0 46.86,-4.536 59.657,-17.321c3.016,-2.999 7.886,-2.995 10.885,0.008c3.008,3.011 3.003,7.882 -0.008,10.889Zm-5.23,-48.781c-16.373,0 -29.701,-13.324 -29.701,-29.698c0,-16.381 13.328,-29.714 29.701,-29.714c16.378,0 29.706,13.333 29.706,29.714c0,16.374 -13.328,29.698 -29.706,29.698Zm-160.386,-29.702c0,-16.381 13.328,-29.71 29.714,-29.71c16.369,0 29.689,13.329 29.689,29.71c0,16.373 -13.32,29.693 -29.689,29.693c-16.386,0 -29.714,-13.32 -29.714,-29.693Z" />
            </svg>
        </a>
    </li>
    <li>
        <a target="_blank" rel="noopener noreferrer" aria-label="share 啪，还敢抛出异常 on facebook"
            href="https://facebook.com/sharer/sharer.php?u=http%3a%2f%2flocalhost%3a1313%2fposts%2fjuejin%2f%25E5%2595%25AA%25E8%25BF%2598%25E6%2595%25A2%25E6%258A%259B%25E5%2587%25BA%25E5%25BC%2582%25E5%25B8%25B8%2f">
            <svg version="1.1" viewBox="0 0 512 512" xml:space="preserve" height="30px" width="30px" fill="currentColor">
                <path
                    d="M449.446,0c34.525,0 62.554,28.03 62.554,62.554l0,386.892c0,34.524 -28.03,62.554 -62.554,62.554l-106.468,0l0,-192.915l66.6,0l12.672,-82.621l-79.272,0l0,-53.617c0,-22.603 11.073,-44.636 46.58,-44.636l36.042,0l0,-70.34c0,0 -32.71,-5.582 -63.982,-5.582c-65.288,0 -107.96,39.569 -107.96,111.204l0,62.971l-72.573,0l0,82.621l72.573,0l0,192.915l-191.104,0c-34.524,0 -62.554,-28.03 -62.554,-62.554l0,-386.892c0,-34.524 28.029,-62.554 62.554,-62.554l386.892,0Z" />
            </svg>
        </a>
    </li>
    <li>
        <a target="_blank" rel="noopener noreferrer" aria-label="share 啪，还敢抛出异常 on whatsapp"
            href="https://api.whatsapp.com/send?text=%e5%95%aa%ef%bc%8c%e8%bf%98%e6%95%a2%e6%8a%9b%e5%87%ba%e5%bc%82%e5%b8%b8%20-%20http%3a%2f%2flocalhost%3a1313%2fposts%2fjuejin%2f%25E5%2595%25AA%25E8%25BF%2598%25E6%2595%25A2%25E6%258A%259B%25E5%2587%25BA%25E5%25BC%2582%25E5%25B8%25B8%2f">
            <svg version="1.1" viewBox="0 0 512 512" xml:space="preserve" height="30px" width="30px" fill="currentColor">
                <path
                    d="M449.446,0c34.525,0 62.554,28.03 62.554,62.554l0,386.892c0,34.524 -28.03,62.554 -62.554,62.554l-386.892,0c-34.524,0 -62.554,-28.03 -62.554,-62.554l0,-386.892c0,-34.524 28.029,-62.554 62.554,-62.554l386.892,0Zm-58.673,127.703c-33.842,-33.881 -78.847,-52.548 -126.798,-52.568c-98.799,0 -179.21,80.405 -179.249,179.234c-0.013,31.593 8.241,62.428 23.927,89.612l-25.429,92.884l95.021,-24.925c26.181,14.28 55.659,21.807 85.658,21.816l0.074,0c98.789,0 179.206,-80.413 179.247,-179.243c0.018,-47.895 -18.61,-92.93 -52.451,-126.81Zm-126.797,275.782l-0.06,0c-26.734,-0.01 -52.954,-7.193 -75.828,-20.767l-5.441,-3.229l-56.386,14.792l15.05,-54.977l-3.542,-5.637c-14.913,-23.72 -22.791,-51.136 -22.779,-79.287c0.033,-82.142 66.867,-148.971 149.046,-148.971c39.793,0.014 77.199,15.531 105.329,43.692c28.128,28.16 43.609,65.592 43.594,105.4c-0.034,82.149 -66.866,148.983 -148.983,148.984Zm81.721,-111.581c-4.479,-2.242 -26.499,-13.075 -30.604,-14.571c-4.105,-1.495 -7.091,-2.241 -10.077,2.241c-2.986,4.483 -11.569,14.572 -14.182,17.562c-2.612,2.988 -5.225,3.364 -9.703,1.12c-4.479,-2.241 -18.91,-6.97 -36.017,-22.23c-13.314,-11.876 -22.304,-26.542 -24.916,-31.026c-2.612,-4.484 -0.279,-6.908 1.963,-9.14c2.016,-2.007 4.48,-5.232 6.719,-7.847c2.24,-2.615 2.986,-4.484 4.479,-7.472c1.493,-2.99 0.747,-5.604 -0.374,-7.846c-1.119,-2.241 -10.077,-24.288 -13.809,-33.256c-3.635,-8.733 -7.327,-7.55 -10.077,-7.688c-2.609,-0.13 -5.598,-0.158 -8.583,-0.158c-2.986,0 -7.839,1.121 -11.944,5.604c-4.105,4.484 -15.675,15.32 -15.675,37.364c0,22.046 16.048,43.342 18.287,46.332c2.24,2.99 31.582,48.227 76.511,67.627c10.685,4.615 19.028,7.371 25.533,9.434c10.728,3.41 20.492,2.929 28.209,1.775c8.605,-1.285 26.499,-10.833 30.231,-21.295c3.732,-10.464 3.732,-19.431 2.612,-21.298c-1.119,-1.869 -4.105,-2.99 -8.583,-5.232Z" />
            </svg>
        </a>
    </li>
    <li>
        <a target="_blank" rel="noopener noreferrer" aria-label="share 啪，还敢抛出异常 on telegram"
            href="https://telegram.me/share/url?text=%e5%95%aa%ef%bc%8c%e8%bf%98%e6%95%a2%e6%8a%9b%e5%87%ba%e5%bc%82%e5%b8%b8&amp;url=http%3a%2f%2flocalhost%3a1313%2fposts%2fjuejin%2f%25E5%2595%25AA%25E8%25BF%2598%25E6%2595%25A2%25E6%258A%259B%25E5%2587%25BA%25E5%25BC%2582%25E5%25B8%25B8%2f">
            <svg version="1.1" xml:space="preserve" viewBox="2 2 28 28" height="30px" width="30px" fill="currentColor">
                <path
                    d="M26.49,29.86H5.5a3.37,3.37,0,0,1-2.47-1,3.35,3.35,0,0,1-1-2.47V5.48A3.36,3.36,0,0,1,3,3,3.37,3.37,0,0,1,5.5,2h21A3.38,3.38,0,0,1,29,3a3.36,3.36,0,0,1,1,2.46V26.37a3.35,3.35,0,0,1-1,2.47A3.38,3.38,0,0,1,26.49,29.86Zm-5.38-6.71a.79.79,0,0,0,.85-.66L24.73,9.24a.55.55,0,0,0-.18-.46.62.62,0,0,0-.41-.17q-.08,0-16.53,6.11a.59.59,0,0,0-.41.59.57.57,0,0,0,.43.52l4,1.24,1.61,4.83a.62.62,0,0,0,.63.43.56.56,0,0,0,.4-.17L16.54,20l4.09,3A.9.9,0,0,0,21.11,23.15ZM13.8,20.71l-1.21-4q8.72-5.55,8.78-5.55c.15,0,.23,0,.23.16a.18.18,0,0,1,0,.06s-2.51,2.3-7.52,6.8Z" />
            </svg>
        </a>
    </li>
    <li>
        <a target="_blank" rel="noopener noreferrer" aria-label="share 啪，还敢抛出异常 on ycombinator"
            href="https://news.ycombinator.com/submitlink?t=%e5%95%aa%ef%bc%8c%e8%bf%98%e6%95%a2%e6%8a%9b%e5%87%ba%e5%bc%82%e5%b8%b8&u=http%3a%2f%2flocalhost%3a1313%2fposts%2fjuejin%2f%25E5%2595%25AA%25E8%25BF%2598%25E6%2595%25A2%25E6%258A%259B%25E5%2587%25BA%25E5%25BC%2582%25E5%25B8%25B8%2f">
            <svg version="1.1" xml:space="preserve" width="30px" height="30px" viewBox="0 0 512 512" fill="currentColor"
                xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape">
                <path
                    d="M449.446 0C483.971 0 512 28.03 512 62.554L512 449.446C512 483.97 483.97 512 449.446 512L62.554 512C28.03 512 0 483.97 0 449.446L0 62.554C0 28.03 28.029 0 62.554 0L449.446 0ZM183.8767 87.9921H121.8427L230.6673 292.4508V424.0079H281.3328V292.4508L390.1575 87.9921H328.1233L256 238.2489z" />
            </svg>
        </a>
    </li>
</ul>

  </footer>
</article>
    </main>
    
<footer class="footer">
        <span><a href="https://beian.miit.gov.cn/">粤ICP备2023039897号-1</a></span> · 

    <span>
        Powered by
        <a href="https://gohugo.io/" rel="noopener noreferrer" target="_blank">Hugo</a> &
        <a href="https://github.com/adityatelange/hugo-PaperMod/" rel="noopener" target="_blank">PaperMod</a>
    </span>
</footer>
<a href="#top" aria-label="go to top" title="Go to Top (Alt + G)" class="top-link" id="top-link" accesskey="g">
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 12 6" fill="currentColor">
        <path d="M12 6H0l6-6z" />
    </svg>
</a>

<script>
    let menu = document.getElementById('menu')
    if (menu) {
        menu.scrollLeft = localStorage.getItem("menu-scroll-position");
        menu.onscroll = function () {
            localStorage.setItem("menu-scroll-position", menu.scrollLeft);
        }
    }

    document.querySelectorAll('a[href^="#"]').forEach(anchor => {
        anchor.addEventListener("click", function (e) {
            e.preventDefault();
            var id = this.getAttribute("href").substr(1);
            if (!window.matchMedia('(prefers-reduced-motion: reduce)').matches) {
                document.querySelector(`[id='${decodeURIComponent(id)}']`).scrollIntoView({
                    behavior: "smooth"
                });
            } else {
                document.querySelector(`[id='${decodeURIComponent(id)}']`).scrollIntoView();
            }
            if (id === "top") {
                history.replaceState(null, null, " ");
            } else {
                history.pushState(null, null, `#${id}`);
            }
        });
    });

</script>
<script>
    var mybutton = document.getElementById("top-link");
    window.onscroll = function () {
        if (document.body.scrollTop > 800 || document.documentElement.scrollTop > 800) {
            mybutton.style.visibility = "visible";
            mybutton.style.opacity = "1";
        } else {
            mybutton.style.visibility = "hidden";
            mybutton.style.opacity = "0";
        }
    };

</script>
<script>
    document.getElementById("theme-toggle").addEventListener("click", () => {
        if (document.body.className.includes("dark")) {
            document.body.classList.remove('dark');
            localStorage.setItem("pref-theme", 'light');
        } else {
            document.body.classList.add('dark');
            localStorage.setItem("pref-theme", 'dark');
        }
    })

</script>
<script>
    document.querySelectorAll('pre > code').forEach((codeblock) => {
        const container = codeblock.parentNode.parentNode;

        const copybutton = document.createElement('button');
        copybutton.classList.add('copy-code');
        copybutton.innerHTML = '复制';

        function copyingDone() {
            copybutton.innerHTML = '已复制！';
            setTimeout(() => {
                copybutton.innerHTML = '复制';
            }, 2000);
        }

        copybutton.addEventListener('click', (cb) => {
            if ('clipboard' in navigator) {
                navigator.clipboard.writeText(codeblock.textContent);
                copyingDone();
                return;
            }

            const range = document.createRange();
            range.selectNodeContents(codeblock);
            const selection = window.getSelection();
            selection.removeAllRanges();
            selection.addRange(range);
            try {
                document.execCommand('copy');
                copyingDone();
            } catch (e) { };
            selection.removeRange(range);
        });

        if (container.classList.contains("highlight")) {
            container.appendChild(copybutton);
        } else if (container.parentNode.firstChild == container) {
            
        } else if (codeblock.parentNode.parentNode.parentNode.parentNode.parentNode.nodeName == "TABLE") {
            
            codeblock.parentNode.parentNode.parentNode.parentNode.parentNode.appendChild(copybutton);
        } else {
            
            codeblock.parentNode.appendChild(copybutton);
        }
    });
</script>
</body>

</html>
